### ISSUE TITLE
LuaPanda.lua 中有全局变量

### ISSUE THREAD

**Issue by sniper00** [Tencent/LuaPanda#105]
**Describe the bug**
这里定义了个全局变量

**Desktop (please complete the following information):**
 - OS: Windows
 - LuaPanda Version "3.2.0"

**Additional context**
https://github.com/Tencent/LuaPanda/blob/04b7d33325915add6b5c9d78c9d3e7cc40ba62d2/Debugger/LuaPanda.lua#L1860

**Comment by stuartwang** [comment]
已接受merge request修复，感谢提交
