### ISSUE TITLE
升级到3.20后无法像3.10那样动态attach到debug

### ISSUE THREAD

**Issue by ShuraLiu** [Tencent/LuaPanda#107]
3.10的时候connectTimeoutSec默认值0.05，在开启openAttachMode后可以在运行游戏后正常动态attach到debug
升到3.20之后connectTimeoutSec默认值还是0.05，但无法动态attach，打开log可以看到一直提示reconnect failed，connectTimeoutSec必须改到1秒或者更长的时间才能attach。
可以确认的是游戏代码没有任何改动，基本判定是LuaPanda升级导致的问题，辛苦开发组的人帮忙看看原因。

**Comment by stuartwang** [comment]
试一下pr的修改， 也感谢raylan大佬的提交
