### ISSUE TITLE
直接使用c api luaL_dostring的调试问题。

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#111]
**Describe the bug**
当直接使用c api luaL_dostring的时候，会出现一个错误提示。

**To Reproduce**
1.autoPathMode设置为true;
2. 当我调用如下代码：
```c++
luaL_dostring(L, (R"+*(require("src.main"))+*"));
```
3. 出现”调试器没有找到文件“的提示（并未影响代码的运行和后续文件的调试）：
![image](https://user-images.githubusercontent.com/30433761/101479944-f5af2400-398d-11eb-8b2a-0fe3dabf0211.png)

**Desktop (please complete the following information):**
 - OS: Windows 64
 - Visual Studio Version 1.51.1
 - LuaPanda Version 3.2.0
 - Lua54

**Comment by stuartwang** [comment]
这里是因为loadstring和loadfile传给调试器的文件路径是不同的
loadfile 传给调试器的是文件路径
loadstring 传给调试器的是[”string“ 字符串内容]
调试器支持loadstring比较麻烦，所以目前是直接过滤掉了，见如下代码

![image](https://user-images.githubusercontent.com/16960038/110727073-86c7bc80-8255-11eb-9f36-3c41ba851cb4.png)

如果调试器弹出这个提示，应该是框架在调用loadstring时给路径前加了"@" , 虚拟机认为传入的是一个文件地址，没有给路径前加上[string。 嘴周调试器提示文件找不到

**Comment by wzhengsen** [comment]
那我改成loadfile的方式吧，谢谢。
