### ISSUE TITLE
显示函数或是属性的注解

### ISSUE THREAD

**Issue by winthropchang** [Tencent/LuaPanda#113]
目前的提示只有函数或是属性的名称
建议可以显示注解，这样我们可以知道更多的讯息

**Comment by winthropchang** [comment]
目前我的做法是和其他的 vscode 插件一起使用
另一个插件有支援显示注解

**Comment by stuartwang** [comment]
可以考虑关闭luapanda的代码提示，仅使用调调试能力 #40
