### ISSUE TITLE
如何裁剪此插件，我只需要debuger调试器子功能，要怎么定制呢？

### ISSUE THREAD

**Issue by zfl9** [Tencent/LuaPanda#118]
如题，此vscode插件，具有如下功能：
- 代码补全（code completion）
- 代码片段（snippet completion）
- 定义跳转（definition）
- 生成注释（comment generation）
- 类型推断（limited type inference）
- 代码格式化（formatting）: 依赖 lua-fmt
- 代码诊断（linting）：依赖 luacheck
- 调试器（debugger）

但是呢，我只需要最后一个子功能（debuger），其它的不需要（太占内存了，导致vscode打开lua工程很卡），而且我已经有其它插件可以实现这些功能，所以请问下大佬，是否有配置可以禁用掉其它子模块？

**Comment by stuartwang** [comment]
修改配置项：可以试下这里，可以禁止除了调试外的其他能力。
![image](https://user-images.githubusercontent.com/16960038/110659726-cc589b00-81fd-11eb-9b99-f9f3d910901e.png)


-------------------------------

剪裁开发：如果想要进行功能剪裁开发的话可以看下源码，红框里面是调试器部分，绿框里是代码辅助部分
![image](https://user-images.githubusercontent.com/16960038/110660571-a5e72f80-81fe-11eb-89fe-295e44d77e36.png)

开发时注意两个模块之间的通信，应该可以把调试器提取出来
![image](https://user-images.githubusercontent.com/16960038/110660744-d5963780-81fe-11eb-8ae0-507bb4b1d972.png)

**Comment by zfl9** [comment]
> 修改配置项：可以试下这里，可以禁止除了调试外的其他能力。

谢谢。
