### ISSUE TITLE
一直等待连接，无法进入调试

### ISSUE THREAD

**Issue by SSmarshal** [Tencent/LuaPanda#119]
**Describe the bug**
运行调试程序的时候，一直提示
[Listening] 调试器 VSCode Server 已启动，正在等待连接。  TargetName:LuaPanda Port:8818

**Expected behavior**
正常进入debug模式

**Screenshots**
![image](https://user-images.githubusercontent.com/46676996/113405430-6b774980-93dc-11eb-8d13-d2053bd88b74.png)

**Additional context**
使用的是ulua
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
luapanda 3.2.0

**Comment by stuartwang** [comment]
无法建立连接时，比较大的可能性是框架中没有集成luasocket。slua ,xlua默认有集成，但ulua我不确定，可以按照下面方法试一下
https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/access-guidelines.md#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

因为调试器lua端要和vscode端建立连接，所以必须框架中必须集成luasocket才能使用

**Comment by SSmarshal** [comment]
您好，我尝试过require "socket.core"但是没有报错
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> require "socket.core"

**Comment by stuartwang** [comment]
这种情况如果是偶现的话，可能是我们的socket连接代码有问题。处理方案是关闭vscode再重新打开，让连接重置一下。
如果是必现，且从没连接成功，可以从以下两点考虑
1. 如果是远成调试（调试手机进程），考虑目标ip和端口填写是否正确
2. 如果是本地调试，考虑默认端口8818是否被占用，可以用命令查询一下端口使用情况

**Comment by ljz** [comment]
> 

你这个就是没有设置luasocket的路径，没有设置对。
