### ISSUE TITLE
Problems with Autocomplete/Intellisense

### ISSUE THREAD

**Issue by delscorcho** [Tencent/LuaPanda#123]
**Describe the bug**
Autocomplete features aren't functional.

I'm only getting very basic autocomplete of certain tokens. I don't see function comments, nor do I get clickable "go to definition" links as shown in your docs.

Furthermore, I tried using the Intellisense folder + Generate button, but none of the symbols in the lua files that live in that folder are showing up in autocomplete.

Is there a setting or configuration that needs to be enabled for autocomplete to be enabled with LuaPanda? Do I need to install another plugin?

Any help is greatly appreciated! Please reach out if you have any questions.

**To Reproduce**
Steps to reproduce the first behavior:
1. Install VS Code
2. Install LuaPanda
3. Type out a function call that exists in the same file
4. Observe lack of clickable "go to definition" link

Steps to reproduce the second behavior:
1. Install VS Code
2. Install LuaPanda
3. Click the LuaPanda status bar button, enter an Intellisense folder, click Generate, restart VS Code
4. Observe no autocomplete for symbols in the above specified folder

**Expected behavior**
Based on the documentation, I expected the above features/functionality.

**Screenshots**
MyFunc is not clickable (first issue)
![image](https://user-images.githubusercontent.com/7051790/117352338-b95ff100-ae63-11eb-84a8-2088a09630fc.png)

The second issue doesn't really need a screenshot.

**Desktop (please complete the following information):**
 - OS: Win10
 - Visual Studio Code 1.56.0
 - LuaPanda Version 3.2.0
 - Using UnLua-exported intellisense

**Comment by stuartwang** [comment]
Sorry for the late reply. 
I tested the first issue, if it still fails to autocomplete, you can try the following steps
1. Use VScode to open a folder and create a lua file in it. 
Becaue LuaPanda Extension can‘t work in temporary files
2. Enter the code and fix the error
Code Error will stop the AST generation, this may cause some symbols can’t be unrecognized
3. The generated symbols will be displayed in outline window
If no symbols in outline, LuaPanda may has some problem while running.
![image](https://user-images.githubusercontent.com/16960038/118525349-a86f8380-b771-11eb-831b-201b305b25cb.png)
4. If outline show tokens, try to right click token or press CTRL + left click , while jump to token definition line.
![image](https://user-images.githubusercontent.com/16960038/118525385-b2918200-b771-11eb-9f31-b074fee064ee.png)

For the second question , I'm sorry now Generate only support slua and slua - unreal , not support UnLua.
![image](https://user-images.githubusercontent.com/16960038/118525640-013f1c00-b772-11eb-80a5-c441c3073b38.png)

Third question， this toggle is set wherther open autocomplete , when it is turned on, the code assist feature is enabled， no need toinstall other plugins.
![image](https://user-images.githubusercontent.com/16960038/118526659-0fda0300-b773-11eb-8d64-a1b6b2131ca2.png)

Thanks for the issue,  if still have problem,  please continue to leave a message

**Comment by delscorcho** [comment]
Thank you for the information, Stuart!
