### ISSUE TITLE
求lua504.exe源码

### ISSUE THREAD

**Issue by zifanzilog** [Tencent/LuaPanda#127]
我需要重新构建lua.exe，例子中的lua504.exe我可以调试，但是自己下载lua源码构建的lua.exe无法调试。求源码学习

**Comment by stuartwang** [comment]
我的源码也是从lua官网下载的，并没有做修改
https://www.lua.org/ftp/lua-5.4.1.tar.gz
自行编译的代码无法调试可能是找不到luasocket，504test中除了有lua504.exe， socket/core也是需要的。文档如下
https://github.com/Tencent/LuaPanda/tree/c5ef26fb52fb5d91cebea623178678f6091c1c64/lua504Test

**Comment by zifanzilog** [comment]
> 我的源码也是从lua官网下载的，并没有做修改
> https://www.lua.org/ftp/lua-5.4.1.tar.gz
> 自行编译的代码无法调试可能是找不到luasocket，504test中除了有lua504.exe， socket/core也是需要的。文档如下
> https://github.com/Tencent/LuaPanda/tree/c5ef26fb52fb5d91cebea623178678f6091c1c64/lua504Test


请大佬给个luasocket的win系统源码，我从官网下载的luasocket 2.0.2编译失败，找不到<sys/un.h> 头文件，百度后发现是linux系统的头文件。如何进行修改？实在找不到资料，我希望能编译出跟你socket/core一样的dll文件来支持我自己编译的lua.exe，我调用你的64位core.dll，没有任何反应，也没有任何报错。不知道问题出现在哪里，我只能尝试自己编译源码。

**Comment by stuartwang** [comment]
https://github.com/Tencent/LuaPanda/tree/master/luasocketBin
