### ISSUE TITLE
vscode关闭调试时，中断整个lua程序

### ISSUE THREAD

**Issue by zifanzilog** [Tencent/LuaPanda#128]
LuaPanda.lua

--断开连接
function this.disconnect()
    --该函数最后加上
    error("中断程序")
end

当vscode调试点击关闭时会调用断开连接函数，lua程序还会继续执行整个程序的代码，死循环也不会停止。所以我加了这个报错机制，来实现中断。
不知道还有没有其他方法可以实现更优雅的中断？

**Comment by stuartwang** [comment]
开发时我是希望当用户停止调试时，调试器断开与lua的连接后，lua程序继续运行。并且调试器后续也可以再次attach上调试器。
如果希望断开连接时lua代码同时停止运行，可以试下这个方法
![image](https://user-images.githubusercontent.com/16960038/120076535-a1813300-c0d8-11eb-8e2b-a589b1c06bc2.png)
http://www.lua.org/manual/5.4/manual.html#pdf-os.exit

**Comment by zifanzilog** [comment]
> 开发时我是希望当用户停止调试时，调试器断开与lua的连接后，lua程序继续运行。并且调试器后续也可以再次attach上调试器。
> 如果希望断开连接时lua代码同时停止运行，可以试下这个方法
> ![image](https://user-images.githubusercontent.com/16960038/120076535-a1813300-c0d8-11eb-8e2b-a589b1c06bc2.png)
> http://www.lua.org/manual/5.4/manual.html#pdf-os.exit

感谢回复，很多疑问想请教大佬，不知大佬可有收费学习课程？我目前正在学习如何使用LuaPanda对我的项目进行远程调试，但是遇到很多问题。LuaPanda是否有演示视频？一个星期还没研究透它的所有功能。

**Comment by stuartwang** [comment]
抱歉最新项目特别忙，所以没有及时回复。
看到留言我也意识到可能之前的文档建设还不够，目前没有做视频也没有特别的收费课程，文档全部集中在这里了
https://github.com/Tencent/LuaPanda/tree/master/Docs
如果对调试器源码或者使用有什么疑问，直接开issue给我留言吧，我会一两天关注一次
