### ISSUE TITLE
扩展无法启动

### ISSUE THREAD

**Issue by senlinding** [Tencent/LuaPanda#132]
![image](https://user-images.githubusercontent.com/4864830/125240661-f8f00100-e31c-11eb-812b-c88295b4eec1.png)

该目录已在.gitignore

**Comment by stuartwang** [comment]
我看到是依赖库 path-reader 出错了，可以考虑更新下 path-reader 最新版本。另外我们没有在linux下测试vscode插件，可能会遇到一些异常，建议在win或者mac下使用
