### ISSUE TITLE
挂载调试器后帧率很低，有什么提高效率的配置吗？

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/LuaPanda#14]
如题

**Comment by stuartwang** [comment]
这个问题有两种可能性：
1. 请把 launch.json 文件中的 logLevel (日志级别)设置为1或者2。
2. 没能成功加载调试器的C模块
解释下第二点，我们分别用lua和c实现了调试器的主体，使用c模块会有较好的性能。调试器也默认会使用c模块，但也可能因为各种原因此模块没能成功加载。

测试方法：调试运行到断点处时，在调试控制台输入`LuaPanda.getInfo()` 返回信息中如果包含
"hookLib Ver:" 那么表示使用了c模块进行调试。

希望能够把开发环境告诉我们，以便我们测试
包含：unity/ue版本，使用的框架名称（slua/ slua-unreal ... ），LuaPanda.getInfo()的返回信息，OS: win/mac
非常感谢

**Comment by sophiepeithos** [comment]
unity 2018.3.8f1
xlua v2.1.14
Lua Ver:Lua 5.3 | Debugger Ver:1.9.15 | supportREPL:1
windows 10 专业版 1809， 17763.107
多谢

**Comment by stuartwang** [comment]
看到原因了，确实是未能使用C模块
我看到使用的的Debugger Ver是1.9.15的，建议更新到2.0.0，旧版本对C模块的支持不太好。
路径如下，把下面两个lua文件替换工程中的同名文件即可。
https://github.com/Tencent/LuaPanda/tree/master/Debugger
配合LuaPanda 2.0.0 版本的 VSCode 插件试一下哈

**Comment by sophiepeithos** [comment]
从两三帧到十五帧了，很好！
还有上升的可能吗？

**Comment by stuartwang** [comment]
如果希望提高执行效率，可以尝试以下几点
1. 尽量不要再每帧刷新的lua逻辑中打[条件断点]
条件断点的反复执行会降低调试帧数。

2. 去除非必要的断点
我们会根据断点的密集程度决定调试器hook频率，可以尝试去除一些非必要的断点，看效率有无提升。其中一种特殊情况是进入调试但全局无断点，这种环境下应该可以看到帧数有所上升。

3. 日志等级
launch.json中有Loglevel选项，这里的日志是定位调试器问题用的。如果正常使用，日志等级保持1或者2就行。

后续我们也会尽量优化寻找提升效率的办法

**Comment by sophiepeithos** [comment]
多谢！
