### ISSUE TITLE
lua5.1能连上，但是断点断不下来

### ISSUE THREAD

**Issue by hw233** [Tencent/LuaPanda#142]
![image](https://user-images.githubusercontent.com/7871927/141246333-658b7c40-1ecd-471e-95a7-433acae2c9df.png)
如图，vscode1.62.1已经连上了，但是断不下来，luasocket是我下载官方编译好的直接用的dll,不知道给这个是否有关系？

**Comment by stuartwang** [comment]
我看已经提示建立连接了，基本可以认定luasocket是正常工作的，试下按这个流程能否解决

https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/FAQ.md#%E6%89%A7%E8%A1%8C%E5%88%B0%E6%96%AD%E7%82%B9%E5%A4%84%E6%97%A0%E6%B3%95%E5%81%9C%E6%AD%A2
