### ISSUE TITLE
一堆代码下面有警告下划线 关不掉

### ISSUE THREAD

**Issue by wmj12** [Tencent/LuaPanda#146]
代码下面一堆警告下划线 关不掉

**Comment by wmj12** [comment]
![image](https://user-images.githubusercontent.com/48977403/163531469-4591d854-c107-4752-9f01-ef5886fb1094.png)

**Comment by GrandZhuo** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/12460014/175331022-87075fc3-3220-492d-8435-a5c937c83cc8.png">

设置里搜索 Lua_analyzer 有代码检查相关的配置项，可以设置忽略的全局变量等。如果要完全关闭代码检查功能只需要取消勾选这项即可。
