### ISSUE TITLE
Windows下配置luanch.json启动参数program时, 路径带有空格则启动失败.

### ISSUE THREAD

**Issue by jqknono** [Tencent/LuaPanda#152]
**Describe the bug**

**To Reproduce**
launch.json中配置program参数时, exe路径带空格启动.

报错如下:
```
[Listening] 调试器 VSCode Server 已启动，正在等待连接。  TargetName:LuaPanda Windows 3.x Port:8818
[Warning] 配置文件 launch.json 中的 program 路径有误: 
 + program 配置项的作用是，在调试器开始运行时拉起一个可执行文件（注意不是lua文件）。如无需此功能，建议 program 设置为 "" 或从 launch.json 中删除 program 项。
 + 当前设置的 'C:\Program Files\xxx\xxx.exe' 不存在或不是一个可执行文件。
```

**Expected behavior**
预期能正常启动程序.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by stuartwang** [comment]
感谢提交，已合入。我本以为用转义符就能处理空格，测试了下发现，powershell下转义符确实无法解决路径问题，按照提交中使用& “cmd” 可以解决问题
