### ISSUE TITLE
libpdebug.lua找不到是什么原因

### ISSUE THREAD

**Issue by sweezt** [Tencent/LuaPanda#155]
启动调试的时候require luapanda的过程中提示找不到libpdebug.lua

**Comment by stuartwang** [comment]
看这里哈
![image](https://user-images.githubusercontent.com/16960038/188393504-f5e57ce6-958a-408f-8a90-566fdbdfd5a8.png)

https://github.com/Tencent/LuaPanda/blob/c5ef26fb52fb5d91cebea623178678f6091c1c64/Docs/Manual/FAQ.md#%E5%85%B3%E4%BA%8E%E6%89%BE%E4%B8%8D%E5%88%B0libpdebug%E6%A8%A1%E5%9D%97%E6%8A%A5%E9%94%99
