### ISSUE TITLE
兼容VSCode 1.33

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/LuaPanda#16]
VSCode升级到1.33后无法断点调试

**Comment by stuartwang** [comment]
我们也发现了这个问题。vscode本次更新似乎修改了win下断点文件的盘符大小。已更新 master 分支的LuaPanda.lua, 版本是2.0.1 , 替换这个文件试一下~

**Comment by stuartwang** [comment]
我们也发现了这个问题。vscode本次更新似乎改变了win下有断点文件的盘符的大小写。已更新 master 分支的LuaPanda.lua, 版本是2.0.1 , 替换这个文件试一下~

**Comment by sophiepeithos** [comment]
已解决，多谢
