### ISSUE TITLE
关于Arm架构 lipDebug支持的问题 

### ISSUE THREAD

**Issue by wenwenaihehe** [Tencent/LuaPanda#166]
能否 添加lipdebug的cmake，目前没有支持 macarm架构的调试Lipdebug

**Comment by stuartwang** [comment]
好的，我最近处理一下

**Comment by stuartwang** [comment]
https://github.com/Tencent/LuaPanda/tree/dev/Debugger/debugger_lib/plugins/mac/arm_64/503
5.3 的库已提交，但目前暂时还不打算发vscode版本。所以去如上地址中取出来arm库之后，替换到
/Users/YOUR_NAME/.vscode/extensions/stuartwang.luapanda-3.2.0/Debugger/debugger_lib/plugins/mac/x86_64/503
下覆盖原文件即可。
---
有其他版本需求也可以自行编译ibpdebug.so，libpdebug库的编译方法，切换到项目`Debugger/debugge
r_lib` 目录下，使用g++或是其他编译器编译即可
g++ -shared -o libpdebug.so libpdebug.cpp -I/usr/local/include  -L/usr/local/lib -llua
