### ISSUE TITLE
全局变量的value可能为空

### ISSUE THREAD

**Issue by Weiged** [Tencent/LuaPanda#17]
![image](https://user-images.githubusercontent.com/41810718/57212654-001d7500-7017-11e9-8c36-137b1b856651.png)
"var.value"可能是空的，然后".."就会报错

**Comment by stuartwang** [comment]
收到，我们近期排查一下

**Comment by stuartwang** [comment]
虽然我们没能复现这个情况，但加入了一些异常处理。对 this.getTableMemberNum 的返回值做了修改。

**Comment by stuartwang** [comment]
> ![image](https://user-images.githubusercontent.com/41810718/57212654-001d7500-7017-11e9-8c36-137b1b856651.png)
> "var.value"可能是空的，然后".."就会报错

虽然我们没能复现，但在这里加入了上面的异常处理。另外也修改了 this.getTableMemberNum 的返回值，即使参数不是table也返回0，避免返回nil在成拼接错误。 
以上修改已提交dev分支，测试后下个版本发布。非常感谢
