### ISSUE TITLE
更新到vscode 1.82后，插件报错无法运行

### ISSUE THREAD

**Issue by evilzhou** [Tencent/LuaPanda#171]
The Lua Analyzer server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by fox1989** [comment]
俺也一样
<img width="1526" alt="企业微信截图_16950309331851" src="https://github.com/Tencent/LuaPanda/assets/3354085/621c2f71-6a92-45ba-97fe-175be7898651">

![image](https://github.com/Tencent/LuaPanda/assets/3354085/8171353d-2945-4841-9927-5eb637e1e712)

**Comment by stuartwang** [comment]
我测试了下，在 windows 1.82.2 版本复现了问题，我最近处理下。预计需要把vscode插件更新一个版本，优先保证调试器功能正常使用

**Comment by fox1989** [comment]
> 俺也一样 <img alt="企业微信截图_16950309331851" width="1526" src="https://user-images.githubusercontent.com/3354085/268611665-621c2f71-6a92-45ba-97fe-175be7898651.png">
> 
> ![image](https://user-images.githubusercontent.com/3354085/268611736-8171353d-2945-4841-9927-5eb637e1e712.png)

暂时用 1.75.1 可用

**Comment by stuartwang** [comment]
我试了下 1.80 可用，1.82 会报错，win和mac都是这样。

如上面截图，错误来源是 web-tree-sitter 插件。但是很多插件依赖的版本比较老了，升级之后直接编译会报错，明天整理下依赖关系

**Comment by stuartwang** [comment]
已发布 3.3.1 版本，适用于 vscode 1.8.2+
