### ISSUE TITLE
没有 用于IntlliSense的cpp 菜单

### ISSUE THREAD

**Issue by krikommp** [Tencent/LuaPanda#173]
LuaPanda 插件版本 v3.3.1
Vscode 版本 1.83.1

LuaPanda Settings 下面没有 用于IntelliSense的cpp文件夹路径 的菜单

![Snipaste_2023-11-01_22-52-14](https://github.com/Tencent/LuaPanda/assets/55438471/947455b2-74df-4e94-ae57-9e88bc18503d)

**Comment by krikommp** [comment]
![Snipaste_2023-11-06_13-28-55](https://github.com/Tencent/LuaPanda/assets/55438471/120bf256-7fdb-4cbe-a24e-93e47f191c41)

原来是这次更新暂时把这个功能关闭了

**Comment by stuartwang** [comment]
是的呀，因为这个功能依赖的univac库很久没有更新过，在vscode1.82版本中有报错，导致调试插件整体无法运行，就把相关功能删掉了。

相关issue #171
