### ISSUE TITLE
希望在独立脚本执行的lanuch配置中，可以使用args的参数

### ISSUE THREAD

**Issue by fanwucoder** [Tencent/LuaPanda#174]
独立脚本运行，本身就应该有完整的程序特性支持，现在在vscode中，args参数无效，希望可以支持。
特别是用busted等单元测试框架时，有时需要控制参数，谢谢

**Comment by fanwucoder** [comment]
我找到了一种替代方式，使用一个脚本将lua可执行程序进行包装，包装后内容如下
lua  "$@"  xxx xx

**Comment by stuartwang** [comment]
我看了下源码，执行独立脚本的时候，拿到 launch.json 中用户设置的luaPath之后，拼接成了
luaPath -e "require('LuaPanda').start('127.0.0.1', port)" 当前打开的文件路径
这样格式的命令，目前没有读取args。
这里处理应该不复杂，我最近加上

![image](https://github.com/Tencent/LuaPanda/assets/16960038/80218b0f-72c7-41ae-b449-15c1a58ffb22)

**Comment by stuartwang** [comment]
功能已完成，随下个版本更新
