### ISSUE TITLE
调试递归调用时，局部变量获取错误

### ISSUE THREAD

**Issue by pilaoda** [Tencent/LuaPanda#177]
https://github.com/Tencent/LuaPanda/blob/e3ac3d3314f24cf939c36cac5b7dc1f2ed6ee129/Debugger/LuaPanda.lua#L1246

看了下源码，应该是这行代码导致的，只要是堆栈里有相同的函数，就只能错误的获取到最上层的堆栈。
请教下为何要用这个方式去获取层数，直接使用`vscode`传过来的`stackId`会有什么问题吗？

**Comment by stuartwang** [comment]
最近有点忙，刚看到消息。
非常感谢提出这个问题。我回顾了一下代码，这里确实是一个bug。因为 `getSpecificFunctionStackLevel` 会从栈顶开始逐层查找函数对应的栈帧，当一个函数存在于两个栈帧中，其中的局部变量处理就只会展示最上层栈帧的。同时这个错误有可能出现在 watch 窗口。

之所以会需要 `getSpecificFunctionStackLevel` 这个函数修正偏移，原因是在 lua 栈中，可能存在存在穿插 native 堆栈的情况。但是把堆栈信息发送给 vscode 时，把 native 栈过滤掉了( 参考 `getStackTable()` ，它的返回值就是前端获得的堆栈)。于是出现了 vscode 发到后端的堆栈并不是实际 stackId 的情况。

总的来说，可以考虑在构建前端堆栈时，不去除 native 原生栈，这样可以保持前后端堆栈对应。 如果保持过滤 native 栈，就要在后端建立映射表。

最近做了一些 js 相关的工作，也参考了下 js 调试器，后续我更倾向于保留 native 堆栈。

**Comment by pilaoda** [comment]
```
function this.getHookOffset()
	if hookLib ~= nil then
		return HOOK_LEVEL;
	end
	
	local funclayer = 0;
	repeat
		local info = debug.getinfo(funclayer, "SlLnf");
		if info ~= nil and info.func == this.real_hook_process then
			return funclayer;
		end
		funclayer = funclayer + 1;
	until not info

	return 0;
end
```

```
-- dataProcess里面
local hookOffset = this.getHookOffset(); --去除偏移量
local stackId = this.curStackId - 1 + hookOffset;
local varTable = this.getVariable(stackId, true);
msgTab.info = varTable;
```

我自己本地改了一下，获取real_hook_process的层级再减一下，就知道真实的堆栈层级了

**Comment by pilaoda** [comment]
其实就是调用 real_hook_process 里面，有可能多次递归调用 receiveMessage，dataProcess这几个函数，导致真实的 lua 层数距离断点所在的层数偏移不固定，只要从 real_hook_process 所在层数去算就能过滤掉所有 debugger 的层数了

**Comment by stuartwang** [comment]
![image](https://github.com/Tencent/LuaPanda/assets/16960038/d3e73d04-9ec3-49dc-ba03-52668ae0389d)


我画了张图表达上面的方案，这样改很好，这部分代码后面会使用你的方案修改。

上面我说得是另一个场景，即 lua 用户栈嵌套原生栈帧的问题。之前的处理方案不太好，容易引发变量和栈帧不匹配的bug，我最近一起优化。

**Comment by stuartwang** [comment]
fix 9bb31aa19fe18a70aec7a0459df7bfda5bb5e5f0
