### ISSUE TITLE
能否检测到Lua死循环？

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/LuaPanda#19]
RT，出现死循环的话，好像调试器也被卡死了？

**Comment by jerry-zeng** [comment]
进每个函数时记录一下时间，然后过了10秒钟还没退出函数，要么是效率非常低的算法，要么是资源加载卡，要么就是死循环，把这个时间设置大一点，就只剩死循环了。不过这可能需要再开个线程或者什么的，好在是调试器，基本都是在电脑上运行，应该没什么隐患，就是有点麻烦。
用的人肯定是希望越简单越好，开发的话难度只有做过的才知道，有兴趣就考虑一下咯，没有也没问题，不影响使用。

**Comment by stuartwang** [comment]
关于lua死循环
当lua出现死循环的时候，lua所在进程会被卡死。比如出现在unity中，会把unity卡死。代码出现死循环时，调试器仍需不断hook用户代码，也就陷入了死循环。

关于代码效率监控
我们做过 profiler 技术预研，每次lua函数调用时记录一个时间戳，返回时再记录一个时间，二者之差得到函数耗时，之后把每个函数耗时组织成树状结构展示给用户，提示用户哪些函数耗时较长需要优化。
因目前主要工作集中在调试功能的优化和bug修复上，profiler和内存分析功能规划会较晚一些。

感谢关注和提出建议~
