### ISSUE TITLE
试用了新的docPathReplace配置功能，反馈一个问题

### ISSUE THREAD

**Issue by lhead** [Tencent/LuaPanda#20]
**Describe the bug**
在被替换的A目录打断点，会在替换后的B目录触发断点。直接在B目录打断点，不触发。

**To Reproduce**
1. 配置替换路径"docPathReplace": ["A", "B"]
2.在A目录1.lua设置断点，会在B目录1.lua的相同行触发断点

**Expected behavior**
在B目录的文件打断点，可以在该文件触发断点

**Comment by stuartwang** [comment]
好的，已收到并定位了问题，近两天修复后会在这里反馈

**Comment by stuartwang** [comment]
我们在dev分之下 d369d8ed890a8c9bf06c4cb4397386724ef44471 修复了此问题，并做了自测。如果还有什么问题欢迎反馈~
简单描述一下思路：
docPathReplace": ["A", "B"]
我们把目录分为A:运行路径 和 B:观察路径
前提: 用户保证运行路径A 和观察路径B 的代码是完全相同的，否则调试时行号会错乱
操作:
调试器启动时会自动把 B 下的断点位置替换成 A, 以便运行时判断断点命中（本次提交新加入的），
命中断点后，用户把堆栈中 A 路径替换回 B ，便于VSCode展示文件给用户看

**Comment by lhead** [comment]
目前使用良好，没发现问题，非常感谢！

另外想请教一下，我们开发环境是Mac+iOS模拟器，这种情况下是不是就没法使用attach模式了？

**Comment by stuartwang** [comment]
理论上是可以使用的，因为attach模式是LuaPanda.lua 在游戏运行期间定期(默认1s)尝试连接VScode端，在实现上和启动时初次连接没有太大区别。需要注意的是，在进行attach连接时，要能执行到lua代码，这样调试器才有机会向VScode发起连接。（我们自己的项目也遇到这个问题，需要点一下界面上的按钮，触发lua代码执行，才能attach上）

如果仍无法使用，可以把LuaPanda.lua更新到最新，并尝试调整几个参数：
1 function this.reGetSock() 中 sock:settimeout(0.05); 表示每次连接等待50ms, 可以适当改长一点。但因为是同步连接，时间过长会造成卡顿。
2 在 LuaPanda.lua 搜索 openAttachMode，能找到两处。其后有一行debug.sethook() ,  把其中的参数1000000 改小一些。这个值表示经过多少次lua return才尝试做一次attach连接。

**Comment by lhead** [comment]
尝试调节了多次参数，但都没有成功。
一个新的发现是，游戏中途开始调试，然后游戏退出登录，这时会重新执行main.lua，之后就会正常触发断点，不过这其实就相当于普通模式了。而如果在调试状态下退出登录，就会中断调试，可能是连接周期没到的缘故，此时虽然重新执行了main.lua，但也不会开始新的调试。
我们的项目是纯lua写的，代码有40M，所以一直会有lua代码在执行，猜测可能是没有直接从C++执行一个lua文件，就不会触发attach？

其实对attach模式也没有硬性需求，但觉得如果可以中途调试的话，工作效率应该会更高一些：）

**Comment by stuartwang** [comment]
我看了整个过程，确实只进行了一次连接，但从这些表现目前还无法推断出具体问题所在。我想后面加一些attach相关日志，这样可以配合日志定位问题。另外记得检查下LuaPanda.lua文件中的开关
local openAttachMode = true;

attach模式我们自己也在用，确实会方便一些，尤其是真机调试。
这个问题我们会持续关注，希望能帮你们解决问题

**Comment by stuartwang** [comment]
我们发布了一个新版本，可以试一下哈。我们自测时也着重关注了attach,  但在我们的工程中没有复现attach连接不上的问题。
这里给一些建议，可以关注下LuaPanda.lua的 disconnect 函数，看它在断开连接时是否正常执行。另外关注reConnect函数，它主要实现了attach功能，在断开连接后，应该会被已每秒1次的频率被不断调用，它主要尝试做网络连接，建立连接之后，发送初始化消息完成attach连接。
可以这些函数中打一些日志观察它们的运行状态。
