### ISSUE TITLE
只有开启stopOnEntry后才能命中断点怎么解决呢？

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/LuaPanda#21]
如题

**Comment by stuartwang** [comment]
也就是设置stopOnEntry : true后，断点可以正常停止。但是stopOnEntry: false后，断点无法响应对么？

我们之前的测试遇到过类似问题，不知道和你的情况是否一样，我先描述一下。
VSCode把断点位置发给lua调试器是在一条独立协议中，在没有断点的情况下，VSCode就不发这条消息。
所以调试器lua端在开始运行时，会停下来等待一小段时间，用于接收断点信息，之后继续运行。
我们遇到的情况是断点信息发来的比较慢，错过了等待时机，而原本的断点位置已经执行过了，造成断点没有停止。
如果是这种情况建议打开stopOnEntry。

但如果不是这种情况，就可能是bug，请做一些更详细的描述，我们复现后修复
