### ISSUE TITLE
开启useCHook并且关闭stopOnEntry会导致Unity关闭的一个问题

### ISSUE THREAD

**Issue by koalli** [Tencent/LuaPanda#22]
环境：
Unity：2018.4.0f1
XLua：2.1.14
vscode：1.35.1

重现步骤：
1、开启useCHook，关闭stopOnEntry
2、Unity中点击Play
3、vscode中按F5启动调试器
4、停止Unity并重新Play
此时Unity卡死，在vscode中停止调试后Unity恢复，但是点击能触发断点的地方会直接关闭Unity。经过测试，如果关闭useCHook或者开启stopOnEntry，以上步骤就不会导致Unity关闭。

**Comment by stuartwang** [comment]
感谢这么详细的测试。我们复现了一下，初步定位为时序问题，此问题在非每帧都会执行lua的工程中可以触发。

建议先打开 stopOnEntry 模式，我们后续会定位并修复。非常感谢。

**Comment by stuartwang** [comment]
我们重新测试了这个问题，xlua示例工程7_AsyncTest在项目停止运行时，没有 dispose 非托管资源。unity停止运行时，lua虚拟机仍然和调试器建立连接，导致再次运行时调试器时序异常。
这里目前的建议是在此情况下开启stopOnEntry。如果一定要关闭stopOnEntry，可以在LuaPanda.lua文件中任意位置打一个断点，也可以防止unity关闭或卡死的问题。
因为这个异常在修复时会影响主逻辑，我们需要一些时间，后续版本看能否彻底解决。
另外我们在新版本2.2.0修复了出错时直接关闭lua进程(unity)的问题，欢迎更新~

**Comment by koalli** [comment]
虽然没有在unity停止时回收Lua虚拟机，不过我尝试过在unity停止的时候手动断开LuaPanda调试器的连接，但vscode也会退出调试导致调试的体验有点糟糕，每次停止后要再调试就得在vscode里启动调试然后再在unity里面运行，略微有点繁琐，希望后续能改进一下。

我们因为会禁用全局表，然后发现DebugTool.lua的decode_scanArray函数下有个全局变量object，应该是json4lua里面也有这个问题。

**Comment by stuartwang** [comment]
关于每次启动调试都要重新run vscode的情况，我们考虑下有没有优化措施。感谢反馈
decode_scanArray这个函数是完全引用自json4lua没有修改，我看其中确实有一个全局变量object 。如果需要移除这个变量可以考虑自行修改一下，直接把返回值赋给array[index]

**Comment by stuartwang** [comment]
最近我们整理了一下socket连接流程，解决卡死的问题。
造成卡死的本质原因是无法正常断开连接。修复后，连接状态异常可能会造成无法连接，但不会再造成lua进程卡死。
所以如果停止了unity运行时，但发现调试器还处于连接状态（这种情况并不多，因为下次运行到lua代码中的时候，会自动向调试器VScode请求断开连接），这时也要停止并重运行一下调试器，以确保已有连接正常断开。
另外关于每次启动调试都要重新run vscode的情况，我们会在后面版本做一下规划，非常感谢

**Comment by stuartwang** [comment]
3.2.0 自测已修复此问题，版本会在稍后发布
