### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by XiangKeSi-21** [Tencent/LuaPanda#23]
[Debugger Log]:Require clib failed, use Lua to continue debug. Set logLevel to 0 and view the debugger log for more information.
这是什么意思

**Comment by stuartwang** [comment]
调试器带有一个c库，作用是使用c hook取代lua hook加速运行。这个错误的原因是c库无法被正确加载。

**Comment by stuartwang** [comment]
调试器带有一个c库，作用是使用c hook取代lua hook加速运行。这个错误指的是c库无法被正确加载。调试可以正常进行，只是得不到c hook加速。

关于无法加载库的具体原因，可以尝试修改日志等级查看。后续版本会对此做一下优化，提供方便查询日志的办法。
