### ISSUE TITLE
子目录的Lua文件断点没用

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/LuaPanda#24]
之前只是测试了单文件，调试没什么问题。这次项目真的需要调试了，发现除了lua代码入口文件里require同目录的lua可以断点调试，只要在别的目录的，断点都没用。

Lua入口放在Main.lua里面，在main()里面require "Test"，这个同目录的Test脚本是可以被调试的，但是require "Game/Director" ，调用它的start()就不能调试。我猜是接入文档里说的"第二步 路径规范"，print(debug.traceback("debug test"))打印出来的日志：
LUA: debug test
stack traceback:
	Game.Director:89: in method 'start'
	Main:38: in function <Main:18>
	[C]: in function 'xpcall'
	Main:43: in main chunk
	[C]: in function 'require'
	[string "chunk"]:3: in main chunk
UnityEngine.Debug:Log(Object)

文档里说的那几个“测试通过 ”结果都不一样，所以调试器没法定位代码了？看文档，我不能理解，哪一条说明是解决这个问题的。

PS：我们项目是用的Lua文件，没有放在Unity工程里，而且有2个代码目录，为了调试我把其中一个文件夹拷贝到另一个去了，然后在cwd只配一个路径。

**Comment by stuartwang** [comment]
感谢提出问题~
我看了一下，traceback中Game.Director:89: in method 'start'
Game/Director在引用时路径被转换成了Game.Director，取到这个路径时调试器以为Game.Director是一个文件，所以没有命中断点。
为了验证这个问题，可以在Game/Director文件中加入一行LuaPanda.BP()，这句话的作用是运行到这里强制停止。之后再次开始调试，执行到BP()时VSCode应该会弹出一个找不到文件的报错，观察其中的路径，看结尾是否是Game.Director.lua而不是Game/Director.lua。
如果验证是这个问题，按下面方法看能否解决，因为你们项目框架traceback没有输出.lua后缀，可以考虑在调试器中强行把 . 转换为 /
具体做法是在LuaPanda.lua 中 this.getPath()中加入一行  filePath = string.gsub(filePath, "%.", "/");
添加位置如下，试一下哈

function this.getPath( info )
    local filePath = info;
    if type(info) == "table" then
        filePath = info.source;
    end

    filePath = string.gsub(filePath, "%.", "/");
