### ISSUE TITLE
当单步调试以"\0"开头的lua字符串变量时导致调试器无法工作的问题

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#26]
**环境**
1.windows10 64
2.vscode 1.36.1
3.标准lua 5.3.4

**重现**
单步调试如下代码：

local str = "\0a"
local ret = str:find("a")

str值和ret值无法在变量监视器中被自动监视，且调试不能再按F10继续

**Comment by stuartwang** [comment]
感谢反馈~
我们在使用中也发现变量中的特殊字符会影响调试器的执行。主要是特殊字符导致解析json协议出错，最终调试器卡死。
后续版本会对变量中的字符串做base64后再传输，避免上面的问题。这个修改将会在2.2.0版本发布，我们目前正在对此版本进行测试，发布后更新一下lua端和VSCode插件即可。

**Comment by stuartwang** [comment]
2.2.0版本已发布，解决了这个问题，更新版本试一下哈~

**Comment by GrandZhuo** [comment]
修复见这次commit 62899e3e64da070c592e3a1316c500a62b0bffda，感谢使用反馈！
