### ISSUE TITLE
安卓下可以attach调试，IOS下不可以

### ISSUE THREAD

**Issue by lhead** [Tencent/LuaPanda#28]
**Describe the bug**
上次反馈无法attach调试的问题（issue#20），当时是用的IOS模拟器，而最近需要经常打安卓包，发现同样的配置，在安卓下是没问题的。

**Additional context**
另外，我们的IOS包打完之后，在修改包外工作目录的代码，改动会直接对运行中的游戏生效，修改包内的代码反而不生效，不知道用了什么技术，这个会不会有影响？

**Comment by stuartwang** [comment]
第一个问题收到，之后我们再做一下iOS测试。

第二个问题，关于热加载. 我们最初考虑过做 lua hot reload 功能，但评估后认为这个功能由开发框架做比较合适，就没有做相应处理。如果改动的代码在游戏中直接生效的话，应该不是调试器的原因。

**Comment by lhead** [comment]
补充一下：修改完代码，IOS直接生效是因为做了如下操作。开始运行lua之后，如果检测到是IOS模拟器环境，会把脚本的搜索路径替换为mac上的源代码目录，然后在运行中，会检测本地代码改动，发现改动后将改动文件写入临时目录，然后reload该文件。

不知道上述操作是否会影响attach的触发。

**Comment by stuartwang** [comment]
感谢说明~
attach的工作原理比较简单，就是定时发起连接。
我理解 lua hot reload 所做的工作是清除 package.loaded，之后重新加载文件，用新的函数实现替换掉原有的。不同框架下reload方案可能不一样。
我觉得只要reload方案不重启lua虚拟机，应该不会影响到attach。
