### ISSUE TITLE
调试单文件报 reGetSock fail

### ISSUE THREAD

**Issue by darjun** [Tencent/LuaPanda#29]
[LuaPanda] [Error] reGetSock fail
[LuaPanda] [Error] reGetSock fail
D:\lua.exe: ...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:743: attempt to index upvalue 'sock' (a nil value)
stack traceback:
        ...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:743: in function 'reConnect'
        ...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:1607: in function <...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:1606>
        [C]: in function 'sethook'
        ...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:1853: in function 'changeHookState'
        ...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:181: in function 'start'
        (command line):1: in main chunk
        [C]: ?
[LuaPanda] [Error] reGetSock fail
D:\lua.exe: ...ions/stuartwang.luapanda-2.2.0/Debugger/LuaPanda.lua:743: attempt to index upvalue 'sock' (a nil value)

**Comment by stuartwang** [comment]
调试器在运行时，需要和VSCode插件建立tcp通信。this.reGetSock()函数的主要功能就是调用lua socekt, 获取socket实例。
reGetSock fail的原因可能是框架中没有集成luasocket, 导致运行错误，请参照 [接入指引](
https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/access-guidelines.md)
检查一下` require("socket.core"); ` 的返回值.  如果使用的框架是slua-unreal ，请告诉我们版本号，我们检查一下。

**Comment by darjun** [comment]
感谢，安装luasocket这个报错解决了

**Comment by 182baobao** [comment]
请问，你怎么解决的呢？感谢

**Comment by stuartwang** [comment]
问题的原因是lua环境没有安装luasocket。测试方法是在命令行输入lua，然后输入require("socket.core") ,如果有报错就说明没有安装luasocket。
具体的安装方法可以百度 “安装luasocket” 关键字查看
