### ISSUE TITLE
单文件debug，文件分隔符好像被去掉了，提示文件找不到

### ISSUE THREAD

**Issue by darjun** [Tencent/LuaPanda#30]
我调试一个lua文件，路径为 D:/code/lua/main.lua，然后错误提示信息是：

`cannot open d:codeluamain.lua: No such file or directory`

d:codeluamain.lua就是把路径分隔符给去掉了。。。

**Comment by stuartwang** [comment]
问题收到。我做了一下自测但没能复现，写一下定位问题的办法:
在VScode弹出找不到文件的错误提示时不要停止调试，打开VSCode的调试控制台(Debug Console), 输入 `LuaPanda.getInfo()` 看一下返回信息 `- Path Info: ` 中
cwd，getinfo，format三个字段，如果 getinfo 中得到的路径就是 d:codeluamain.lua 这样不带分隔符的，说明lua虚拟机传给调试器的路径就是这样的，可能要看一下lua虚拟机读文件时记录的文件路径是不是没有处理好。如果用的是标准lua环境，没有修改过代码，可以把lua版本号告诉我，我试一下。
如果getinfo 中有分隔符，但是format中没有了，就把 `- Path Info: ` 信息整体粘到这里，我尝试复现一下看如何修复。

**Comment by darjun** [comment]
> 问题收到。我做了一下自测但没能复现，写一下定位问题的办法:
> 
> 在VScode弹出找不到文件的错误提示时不要停止调试，打开VSCode的调试控制台(Debug Console), 输入 `LuaPanda.getInfo()` 看一下返回信息 `- Path Info: ` 中
> cwd，getinfo，format三个字段，如果 getinfo 中得到的路径就是 d:codeluamain.lua 这样不带分隔符的，说明lua虚拟机传给调试器的路径就是这样的，可能要看一下lua虚拟机读文件时记录的文件路径是不是没有处理好。如果用的是标准lua环境，没有修改过代码，可以把lua版本号告诉我，我试一下。
> 
> 如果getinfo 中有分隔符，但是format中没有了，就把 `- Path Info: ` 信息整体粘到这里，我尝试复现一下看如何修复。

感谢回复。

补充一下我的版本信息：
win10 + lua5.1.4

lua可执行程序是我从官方上下载源码，加入了pbc的c源文件编译生成的exe
报这个错之后，右下角弹出stop connecting，调试直接退出了。这时候 DEBUG CONSOLE输入任何都没响应，直接enter会提示"no debug adapter"

**Comment by darjun** [comment]
补充一点：

output窗口输出信息：

[Debugger Log]:Require clib failed, use Lua to continue debug, use LuaPanda.getInfo() for more information.
[Debugger Log]:debugger init success

**Comment by darjun** [comment]
选中要调试的文件 main.lua，然后按 F5 调试，控制台输出：

lua -e  "package.path = 'C:/Users/xxx/.vscode/extensions/stuartwang.luapanda-2.2.0/Debugger/?.lua;D:/code/lua;'.. package.path; require('LuaPanda').start('127.0.0.1',8818);" d:\code\lua\main.lua
E:\tools\lua.exe: cannot open d:codeluamain.lua: No such file or directory

**Comment by stuartwang** [comment]
非常感谢这么详细的说明，我大概知道原因了。
```
lua -e "require('LuaPanda').start('127.0.0.1',8818);" d:\code\lua\main.lua
```
后面路径的转义符在读文件前被处理掉了，初步的想法是把获取到路径的 \ 替换成 / ，再放入命令行执行。 我尝试复现上面问题并测试之后修复。

另外`:Require clib failed, use Lua to continue debug, use LuaPanda.getInfo() for more information`表示没有加载到c调试库，会使用lua库进行调试，不影响调试功能。 后面我们会再查一下win console下的c库引用问题。

**Comment by stuartwang** [comment]
我们已经在dev下提交 c8954a449f6f213dc0b28321821a43c913a68cdd  中修复了此问题。
思路是把win下文件路径中的分隔符\替换为/， 来避免\被当做转义符的问题 ,  比如
```
lua -e "require('LuaPanda').start('127.0.0.1',8818);" d:\code\lua\main.lua
会被替换为
lua -e "require('LuaPanda').start('127.0.0.1',8818);" d:/code/lua/main.lua
```
如有需要可以自行拉取dev代码打包测试。打包方法参考
https://github.com/Tencent/LuaPanda/blob/master/Docs/Development-instructions/project-description.md

**Comment by darjun** [comment]
我测试了一下，已经可以了，非常感谢！！

有个小问题，run打开一个新窗口后，第一次F5，总是会报错：
```
cannot open extension-output-#5: No such file or directory
```

另外问下，这个修改什么时候会更新的vscode的插件上，现在用起来不太方便。

**Comment by stuartwang** [comment]
cannot open extension-output-#5: No such file or directory
这个问题我们也遇到了，应该是vscode启动后第一次获取当前窗口有点问题，我们试下能否通过二次获取窗口解决这个问题。

我们考虑本周末或下周初把插件升级一个小版本到2.2.1（VScode端升级，lua端不变），会包含这个更新。

**Comment by darjun** [comment]
好的，👍👍👍

**Comment by stuartwang** [comment]
已更新，版本是2.2.1。同时修复了 cannot open extension-output-#5 错误问题，可以试一下哈
