### ISSUE TITLE
UE4编辑器play时卡住.

### ISSUE THREAD

**Issue by sichuanke** [Tencent/LuaPanda#32]
在VScode打开时,UE4编辑器点play,偶现会卡住,调试发现一直在等待socket,关闭vscode后,编辑器可以继续运行

**Comment by stuartwang** [comment]
收到，我们也遇到过这个问题。具体表现是VSCode客户端已经停止调试了，但是游戏卡在了某处，关闭VSCode 后恢复正常。
原因看起来是调试器和VScode的连接问题，我们再尝试一下复现修复。
想问下平台是 win/mac，  开发框架是slua-unreal 还是别的？

**Comment by sichuanke** [comment]
开发平台是win,开发框架是 slua-unreal, LuaPanda debugger版本号:"2.2.0"
发现另一个问题在没有开VSCode的情况下,打开UE4,点play也卡主了

**Comment by stuartwang** [comment]
如果没有开vscode 时 ue4 也会卡住的情况，不知道是否是调试器和别的进程建立了链接，可以考虑更换端口试一下。
具体方法是在工程launch.json中改一下`connectionPort`,  同时在`require("LuaPanda").srart("127.0.0.1",8818)`时修改成对应的端口号

**Comment by sichuanke** [comment]
改端口号,这个方式已经这样处理过,上面两种卡住的情况,是在改端口号之后的

**Comment by stuartwang** [comment]
好的，我们做测试尝试复现修复一下

**Comment by stuartwang** [comment]
3.2.0 版本已修复了socket连接的问题，稍后可以在新版本中试一下
