### ISSUE TITLE
这个调试器挺棒的，腾讯为何不做一个编辑器功能

### ISSUE THREAD

**Issue by netroby** [Tencent/LuaPanda#33]
这个调试器挺棒的，腾讯为何不做一个编辑器功能
现在能找到的lua开发工具，都不是很好用，有的甚至要卖钱收费

腾讯这么强啊 ，咋不干脆做一个lua ide（哪怕是基于vscode插件的也行）

能造福千万个luaer

**Comment by stuartwang** [comment]
感谢使用我们的调试器~ 
庞大的公司经过层层组织架构会被分割为很多小团队，我们也是其中之一( Readme文档中有我们的团队介绍 ^^) ，这个调试器就是由我们开发和维护的。
最初开发的目的是供团队内使用，提升lua开发效率。使用一段时间大家觉得对开发有些帮助，就希望开源出来供更多人使用。
最初对外发布的时候，调试器在不同的环境下出现了很多问题，经常需要引导用户提取日志，描述问题，尝试复现和修复。后来质量稳定了一些，工作上又有了很多业务需求，调试器主要依靠业余时间进行开发维护。
因为精力所限，目前主要维护调试器部分，其他暂时不考虑了。现在VSCode插件商店有一些lua辅助工具，可以尝试搜索下。我也尝试开发过lua代码辅助工具，以技术研究为主，产品化做的一般，就不再推荐了。
我觉得这个工作很有趣，自己开发的工具能够给别人带来帮助，也是一件让人开心的事

准备回家了，断断续续随便写了一点。 作为一个普通的工具开发者，希望大家用的开心。
