### ISSUE TITLE
PC调试可以选择进程进行attach吗?

### ISSUE THREAD

**Issue by msccreater** [Tencent/LuaPanda#37]
PC调试工程文件时能选择调试的进程吗?想nodejs那种的

**Comment by stuartwang** [comment]
我的理解是一个运行的lua虚拟机代表一个lua进程，如果存在多个lua虚拟机，那么每个虚拟机都要单独调用require("LuaPanda").start(ip , port) ， 并设置不同的port来区分进程。
以前有后台同学提出他们有很多lua虚拟机，希望调试器可以自动选择进程attach调试，这种场景目前是无法覆盖的。
