### ISSUE TITLE
调试时，鼠标悬停变量显示问题

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#38]
**版本**
LuaPanda 2.3.0
**重现**
```lua
local t = { x = "1"}
print("2"..t.x.."3")
print("2" .. t.x .. "3")
```
如：
* 第一个print中的t.x和字符串连接符之间没有空格时，鼠标悬停时无法正确获取变量值；
* 第二个print中的t.x和字符串连接符之间存在空格时，鼠标悬停时可以正确获取变量值。

另：
number/boolean等类型的字面常量值，鼠标悬停时可以取得字面值；而字符串类型的字面常量，无法获取字面常量值。

**Comment by stuartwang** [comment]
感谢反馈，刚才我查了下原因。
鼠标悬停变量取值的原理是：鼠标悬停时，VSCode自动获取鼠标指向的文本，之后发给调试器插件，插件会把获取到的字符利用 "观察变量/表达式“ 向调试器lua端查值。

当鼠标移到第一行 local t = { x = "1"}   的 x时，我们本意是取t.x，但VSCode获取到的字符串是x, 调试器查到x的值为nil. 不符合预期

当鼠标移到第二行 print("2"..t.x.."3") 的t时，VSCode取到的值是\"2\"..t，调试器用这个表达式求值，得到了错误信息。鼠标移到t.x时，VSCode取到的值是\"2\"..t.x，调试器求值得到2..1，最后返回字符串21

第三行因为有空格分隔，VSCode取到了正确的字符串，所以返回值是正确的。

看到这个issue的时候，我觉得是个有趣的问题。这个错误最终是因为当表达式没有空格的时候vscode没有正确分隔字符，取到了错误的文本，调试器就得到了错误的值。

虽然目前没法直接解决这个问题，建议大家可以
1.对代码进行luaformat，标准的格式有助于提高识别率
2.可以使用观察变量或者调试控制台观察值
