### ISSUE TITLE
package.json配置有误。

### ISSUE THREAD

**Issue by GrandZhuo** [Tencent/LuaPanda#4]
**Describe the bug**
npm install安装vscode模块后无法自动下载vscode.d.ts文件，导致工程中找不到vscode模块。

**To Reproduce**
1. 下载工程，运行npm install。
2. 打开工程编译出错，找不到模块vscode。

**Expected behavior**
工程可以正常编译运行。

**Additional context**
bug原因：package.json中缺失了"postinstall": "node ./node_modules/vscode/bin/install"

**Comment by stuartwang** [comment]
非常感谢，已合并
