### ISSUE TITLE
可不可以给一个开关关闭代码提示

### ISSUE THREAD

**Issue by Weiged** [Tencent/LuaPanda#40]
我已经在使用emmylua作为代码提示的插件了,现在这个不能关,功能又没有Emmy强大,然后提示的时候会出双份干扰,不太爽

**Comment by stuartwang** [comment]
可以的。考虑到大家使用习惯，我会在配置中加一个开关，可以选择打开或是关闭代码提示功能。

**Comment by stuartwang** [comment]
已经加上此功能并作为 3.0.1 版本推到商店了。
具体操作方法是：任意打开一个lua文件，激活插件。点击VScode状态栏左下角的LuaPanda进入可视化配置页面。关闭最后一项lua辅助工具，再重启VSCode即可。
