### ISSUE TITLE
一个说不上来是不是bug的bug

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#44]
**重现步骤**
1. 将“随调试器启动的可执行文件路径”配置后，如下：
"program": "${workspaceRoot}/XXX.exe"
2. 按F5调试，
3. XXX.exe确实运行成功并正确调试了，
4. 关闭XXX.exe，
5. 多重复几次2-4步骤，
6. 发现右下角终端窗口不会自动关闭，并且会越来越多：
![1](https://user-images.githubusercontent.com/30433761/69936658-60c05200-1513-11ea-8128-7931309ad3df.png)

**Comment by stuartwang** [comment]
收到，之前的做法是每次启动一个新的terminal ，用于运行XXX.exe.  后面我们想尝试做一下检测，如果之前创建的terminal没有被销毁，就尝试复用，避免生成很多的情况。
感谢反馈~

**Comment by stuartwang** [comment]
已修复，实现运行 program 时终端的复用，此特性预计跟随下个版本发布。
