### ISSUE TITLE
一个在不合理的时机随调试器启动可执行程序的问题

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#46]
**描述**
program配置所指向的可执行程序在不合理的时机启动了

**重现**
1. program指向xxx.exe；
2. autoReconnect配置为true；
3. 按F5启动，此时，调试是正常的；
4. 在lua端关闭调试器连接；
5. 此时，调试器确实重启并等待连接了；
6. 但是，调试器又启动了一个新的xxx.exe

**Comment by GrandZhuo** [comment]
请问是否是希望在第5步启动调试器后连接到之前运行的程序，而不启动新的程序？

**Comment by wzhengsen** [comment]
在第四步的时候，我其实是把lua栈销毁并立刻创建一个新的lua栈以实现重启，

**Comment by wzhengsen** [comment]
所以，此时程序并未结束，如果此时立刻启动一个新的exe显然是不对的

**Comment by stuart-tc** [comment]
我理解是第四步的操作是销毁，并重启了一个lua虚拟机，整个exe仍在继续运行。此时开启调试，用户希望VSCode直接连接上exe创建的新的虚拟机，而不要重开一个exe。
我想到两种方案解决这个问题。1是连接后记录进程号，并在下一次启动调试时检测上次记录的pid是否还存在，这种实现比较复杂。
另一种是在增加一个调试选项，用户可以在每次启动调试时切换选项，来决定是否拉起exe.

**Comment by stuartwang** [comment]
感谢提出问题，目前的实现方案在这种场景下确实是存在问题的。
我理解是第四步的操作是销毁，并重启了一个lua虚拟机，整个exe仍在继续运行。此时开启调试，用户希望VSCode直接连接上exe创建的新的虚拟机，而不要重开一个exe。
我想到两种方案解决这个问题。1是连接后记录进程号，并在下一次启动调试时检测上次记录的pid是否还存在，这种实现比较复杂，依赖特定平台接口。
另一种是在增加一个调试选项，用户可以在每次启动调试时切换选项，来决定是否拉起exe.
我倾向于第二种方案，因为通用性更强，不依赖特定平台/框架。缺点是用户在启动调试前可能会根据需要选一下配置

**Comment by wzhengsen** [comment]
感谢，第二种确实比较灵活。

**Comment by stuartwang** [comment]
好的，我们先按第二种实现。
预计跟随下个版本发布，发布时我会在这里通知，并关闭issue

**Comment by stuartwang** [comment]
我在配置项中增加了一个 LuaPanda-Attach 的选项，用于进行attach连接。

![image](https://user-images.githubusercontent.com/16960038/71659090-387d7a80-2d81-11ea-84d1-1e2bc887f3cd.png)
