### ISSUE TITLE
无法区分table有两个key是同名number和string

### ISSUE THREAD

**Issue by pilaoda** [Tencent/LuaPanda#47]
![image](https://user-images.githubusercontent.com/12658348/70776449-0c8d5b80-1db8-11ea-95f9-a11811f11422.png)
如图，table有key为1也有key为“1”的kv对，但是断点调试时只能看到其中一个。

**Comment by GrandZhuo** [comment]
这是一个已知问题，当前没有对数字和字符串做判断，我们会在后续版本中完善。感谢issue，也欢迎PR，一起完善LuaPanda。

**Comment by stuartwang** [comment]
![testDemo](https://user-images.githubusercontent.com/16960038/71151313-6d141100-226e-11ea-971f-caf36cccd004.png)
我们尝试修复了这个问题，table中的string key会加上引号，和数字key加以区分。这个修改会随着下一个版本发布。
感谢反馈，如果还有相关问题也可以在这里留言。

**Comment by stuartwang** [comment]
3.1.0新版本已发布，可以试一下~
