### ISSUE TITLE
lualint在处理比较多的lua代码的时候会无法工作

### ISSUE THREAD

**Issue by dayongxie** [Tencent/LuaPanda#49]
**目录中有代码量比较大的Lua代码的时候Lualint无法工作**

如题，具体情况如下

我的项目里面存在一些从excel表导出的Lua文件，这些文件是简单的KeyValue表，数据量比较大，Key是又臭又长的驼峰命名的字符串，当数据多到一定行数后，lualint就无法工作，并且会影响所有的lua文件。

**Comment by stuart-tc** [comment]
我们也注意到在含有大量文件中工程中lualint效率低甚至无法工作的状况，已经有了优化方案，正在重构代码，下个版本就会修复。
另外想问下文件个数或者发生此问题的文件行数有一个大概的量级么？我们开发完成后会找一些类似或量级更大的工程自测。

**Comment by dayongxie** [comment]
我上传了一个可以复现问题的lua文件，只要删除一条数据甚至只要把一条key改短一点，lualint就可以正常工作
[Localization.lua.txt](https://github.com/Tencent/LuaPanda/files/3971271/Localization.lua.txt)

**Comment by stuartwang** [comment]
我们注意到在含有大量文件中工程中lualint效率低甚至无法工作的状况，已经有了优化方案，正在重构代码，下个版本就会修复。
我们也会用这个文件做一下测试，非常感谢~

**Comment by stuartwang** [comment]
已发布新版本3.1.0， 自测修复了这个问题。
可以试一下哈，如仍有问题可以在这里留言

**Comment by dayongxie** [comment]
vscode的LuaPanda已经自动升级到3.1.0版本，用我上传的lua代码试了一下，仍有问题。
这段代码会导致lualint不工作，但是删掉最后一个字段就会出现3处lint提示
