### ISSUE TITLE
自动补全，跳转，格式化等功能无效

### ISSUE THREAD

**Issue by gzgh14** [Tencent/LuaPanda#51]
我在vscode安装了LuaPanda，发现自动补全，转到定义，代码格式化等功能都无法使用，请问是要做什么设置吗

**Comment by stuartwang** [comment]
按下面的操作流程试一下
1. 用vscode打开一个包含lua文件的文件夹（注意这里必须是一个文件夹），并打开其中的一个lua文件
2. 看下vscode状态栏右下角的文件类型是否为lua,  如果不是，点击这里把对应文件的类型切换到lua
![image](https://user-images.githubusercontent.com/16960038/71667284-6671b780-2d9f-11ea-855f-6d7d1ca4437f.png)
原因是有的框架中lua文件是txt或者lua.bytes等后缀的，vscode没有默认把他们识别为lua文件
3.看一下状态栏左下角是否出现LuaPanda标志，如果出现说明插件已经加载。应该就可以正常使用了
![image](https://user-images.githubusercontent.com/16960038/71667367-c4060400-2d9f-11ea-85d0-52b19dff767c.png)
可以按这个步骤试一下，如果还有问题可以在这里留言

**Comment by gzgh14** [comment]
按照这个流程测试了，状态都是对的，但是这些功能还是无法使用。查看了log，好像有报错


| |
zjgh08
|
|
zjgh08@163.com
|
签名由网易邮箱大师定制
在2020年1月2日 20:39，stuartwang<notifications@github.com> 写道：

按下面的操作流程试一下

用vscode打开一个包含lua文件的文件夹（注意这里必须是一个文件夹），并打开其中的一个lua文件
看下vscode状态栏右下角的文件类型是否为lua, 如果不是，点击这里把对应文件的类型切换到lua

原因是有的框架中lua文件是txt或者lua.bytes等后缀的，vscode没有默认把他们识别为lua文件
3.看一下状态栏左下角是否出现LuaPanda标志，如果出现说明插件已经加载。应该就可以正常使用了

可以按这个步骤试一下，如果还有问题可以在这里留言

**Comment by gzgh14** [comment]
按照这个流程测试了，状态都是对的，但是这些功能还是无法使用。查看了log，好像有报错。cant get file content 这个报错忽略，发现时里面没有内容。
经测试，有些文件夹会有这个错误，有些能正常。


| |
zjgh08
|
|
zjgh08@163.com
|
签名由网易邮箱大师定制
在2020年1月2日 20:39，stuartwang<notifications@github.com> 写道：

按下面的操作流程试一下

用vscode打开一个包含lua文件的文件夹（注意这里必须是一个文件夹），并打开其中的一个lua文件
看下vscode状态栏右下角的文件类型是否为lua, 如果不是，点击这里把对应文件的类型切换到lua

原因是有的框架中lua文件是txt或者lua.bytes等后缀的，vscode没有默认把他们识别为lua文件
3.看一下状态栏左下角是否出现LuaPanda标志，如果出现说明插件已经加载。应该就可以正常使用了

可以按这个步骤试一下，如果还有问题可以在这里留言

**Comment by stuartwang** [comment]
can‘t get file content 这个报错可以忽略，通常原因是文件为空。
如果LuaPanda已经成功加载了（VSCode状态栏左下角可以看到可视化界面入口），但无法执行补全或者是跳转有几种可能的原因
1是当前lua代码中存在语法错误。
格式化工具和代码辅助工具的基础是把用户的 lua 代码分析成 AST 语法树，如果代码没有写完或者其中有错误，parser就可能无法正常生成AST, 无法提取代码中的信息，导致在本文件中功能失效。
2是我们发现使用的 parser 对lua中多行注释 --[[  兼容的不好，如果文件中有多行注释，可能导致行号出现问题，最终无法实现功能。

最后记得核对一下LuaPanda插件的版本，保持到3.1.0 。 确认下代码辅助功能打开
![image](https://user-images.githubusercontent.com/16960038/71703776-817d0f80-2e11-11ea-90ea-5e631384e62a.png)

**Comment by stuartwang** [comment]
先试下哈，如果还有什么疑问可以在这里留言

**Comment by bingtian** [comment]
> 按照这个流程测试了，状态都是对的，但是这些功能还是无法使用。查看了log，好像有报错。cant get file content 这个报错忽略，发现时里面没有内容。 经测试，有些文件夹会有这个错误，有些能正常。 ![image](https://user-images.githubusercontent.com/8555639/71702580-3829c180-2e0b-11ea-9257-00d5fb7256c1.png) 按下面的操作流程试一下 用vscode打开一个包含lua文件的文件夹（注意这里必须是一个文件夹），并打开其中的一个lua文件 看下vscode状态栏右下角的文件类型是否为lua, 如果不是，点击这里把对应文件的类型切换到lua 原因是有的框架中lua文件是txt或者lua.bytes等后缀的，vscode没有默认把他们识别为lua文件 3.看一下状态栏左下角是否出现LuaPanda标志，如果出现说明插件已经加载。应该就可以正常使用了 可以按这个步骤试一下，如果还有问题可以在这里留言 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是不是自己封装了函数代替了require，这种情况下，自动补全是有问题的

**Comment by stuartwang** [comment]
这个提示是在分析时有报错，我们后面对这个位置测试并处理一下。
看错误堆栈，像是在解析某种table的成员语法时候没有处理好，有可能是“是不是自己封装了函数代替了require”中有些代码结构没有被语言插件识别

**Comment by CUTEQWQ** [comment]
@stuartwang 你好，想问下parser 对lua中多行注释 --[[ 兼容不好导致功能失效，这块有考虑支持吗，我们项目里还挺多这种多行注释的qwq
