### ISSUE TITLE
lualint在处理比较多的lua代码的时候会无法工作

### ISSUE THREAD

**Issue by dayongxie** [Tencent/LuaPanda#53]
之前提的Issue被关了，但是问题还存在 #49 ，再提一下哈

**Comment by dayongxie** [comment]
自己调试了一下，发现造成这个问题的原因
插件在调用luacheck的时候，命令行参数过长导致的
命令行的参数里包含了项目中所有的全局符号，恰好因为我项目里存在不规范的lua代码

```lua
Localization = {
    AbilityLimitWarnning = "",
    AbortCityWar = "",
    Abroad = "",
    Academy1  = "",
    Academy11  = "",
    Academy12  = "",
    Academy13  = "",
    Academy14  = "",
    Academy15  = "",
    AcademyIncreament = "",
    ActivityCalendar = "",
    ActivityLoginDay = "",
    ActivityFinished = "",
    ActivityLeftTime = "",
    AccountBlock = "",

}
```
以上代码所有的Localization内部字段都会作为全局符号传入到luacheck命令中，导致项目中所有lua文件的lualint都无法正常工作。

**Comment by GrandZhuo** [comment]
感谢反馈！
之前我们用你上传的文件单独测试过，功能正常所以关闭了issue。
关于命令行参数过长导致luacheck功能异常的问题我们会再测试一下。
调用luacheck时将全局符号传递给luacheck是为了避免出现使用未定义的全局符号的warning，因为调用luacheck是针对单个文件的，而文件中使用到的全局符号可能定义在工程中其他文件，所以我们统一忽略了全局符号。
如果传递给luacheck的参数过多会导致luacheck运行异常，我们会在这里做一些处理，初步考虑看是否方便只将本文件内的全局符号传递给luacheck，并对数量做限制。如果你对这个问题有其他见解也可以和我们一起讨论，当然，更欢迎PR，一起参与到LuaPanda的开发维护中！

**Comment by dayongxie** [comment]
谢谢回复，我传的代码里在lua文件中直接将模块声明全局变量的做法应该不符合lua的规范，规范的做法是声明为local，然后在文件末尾return。
所以我认为调用luacheck的时候可以不传代码中的全局符号，有luapanda配置中的全局符号就够了，或者用.luacheckrc配置文件配置全局符号的方案更灵活一些

**Comment by wuyigq** [comment]
@GrandZhuo 我的cocos2dx-lua工程也遇到了同样的问题，查看代码发现原来的luacheck   global参数是将工程中所有全局变量Symbol方式拼接并传入，例如在上面2楼给到的例子只需传入Localization就可以了，但实际上可能会传入 Localization.AbilityLimitWarnning Localization.AbortCityWar  ...这样几十乃至上千个字符串，我提交的PR修改了这个情况，只会传入Localization等顶级全局变量名，@dayongxie 你可以看下有没有解决你的问题

**Comment by GrandZhuo** [comment]
> @GrandZhuo 我的cocos2dx-lua工程也遇到了同样的问题，查看代码发现原来的luacheck global参数是将工程中所有全局变量Symbol方式拼接并传入，例如在上面2楼给到的例子只需传入Localization就可以了，但实际上可能会传入 Localization.AbilityLimitWarnning Localization.AbortCityWar ...这样几十乃至上千个字符串，我提交的PR修改了这个情况，只会传入Localization等顶级全局变量名，@dayongxie 你可以看下有没有解决你的问题

感谢PR！
