### ISSUE TITLE
xlua打断点问题，提示：无法加载源“Init.lua.txt”。

### ISSUE THREAD

**Issue by zackloveyezi** [Tencent/LuaPanda#55]
使用xlua给的例子是可以打断点成功的。用在自己的模块提示：无法加载源“Init.lua.txt”。

**Comment by stuartwang** [comment]
这个是 VSCode 的报错，原因是 VSCode 在打开的项目中没有找到 Init.lua.txt 这个文件。
我猜测逻辑是调试器启动，lua 代码运行到了 Init.lua.txt 这个文件，由于默认开启了stopOnEntry(调试器建立连接时停止)，所以会立刻触发一个断点操作。调试器通知VSCode打开 Init.lua.txt 文件，但VScode没找到这个文件，所以报错了。

建议查一下 VSCode 打开的项目中是否包含 Init.lua.txt 这个文件。另外看一下launch.json中 LuaPanda启动项的"luaFileExtension"是否设置为"lua.txt"。
