### ISSUE TITLE
调试luac文件出现的问题

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#57]
# 环境：
win10 64位
LuaPanda 3.10

# 重现：
1.有文件如下，且工作目录为xxx：
main.lua
xxx/src/Application.lua

2.在main中：
```lua
require("src.LuaPanda").start()
package.path = package.path .. ";src/?.lua";
require("Application")
```

3.在进入"Application"文件后，查看LuaPanda.getInfo()：
debugger: xxx/src/LuaPanda.lua
cwd:      xxx/
getinfo:  @src/Application.lua
format:   xxx/src/Application.lua
>到现在为止，一切正常。

4.将Application.lua替换为Application.luac，重新开始1-3步骤：
debugger: xxx/src/LuaPanda.lua
cwd:      xxx/
getinfo:  @Application.lua    <- 这里的src的目录消失了。
format:   xxx/Application.lua    <- 这个文件不存在，无法调试。

**Comment by stuartwang** [comment]
收到。说一下我的理解哈。
getinfo 获取到的路径是从lua虚拟机里传来的，目前看到的问题是在字节码的情况下，从虚拟机中传来的路径烧了/src层级。
从我们之前的使用经验，在使用luac编译字节码的时候，文件的路径会被记住。也就是编译出来的luac文件会记住之前lua文件的路径。举个例子
```
luac -l ./test.lua
   输出的字节码：
main <./test1.lua:0,0> (8 instructions at 0x7fa7a7c022c0)
0+ params, 2 slots, 1 upvalue, 2 locals, 5 constants, 0 functions
        1       [1]     GETTABUP        0 0 -1  ; _ENV "require"
        2       [1]     LOADK           1 -2    ; "LuaPanda"
        3       [1]     CALL            0 2 2
        4       [1]     GETTABLE        0 0 -3  ; "start"
        5       [1]     CALL            0 1 1
        6       [2]     LOADK           0 -4    ; 9
        7       [3]     LOADK           1 -5    ; 12
        8       [3]     RETURN          0 1
```
第一行记录了lua文件的位置。之后不管这个字节码文件移动到哪里，执行它的时候，返回的路径始终是他记录的路径。
所以我在想，如果编译Application.lua的时候，使用的是`luac -o Application.luac Application.lua`
那么编译出的luac记录的文件路径就是Application.lua ,最终getInfo输出变成了Application.lua
如果使用`luac -o Application.luac src/Application.lua` 编译出的文件可能就没有这个问题。

另外想确认一点，我看工程没有使用自动路径模式对吧。可以尝试用下,  能解决这个问题
使用方式是在Launch.json中打开            "autoPathMode": true,
cwd设置为workspaceFolder                   "cwd": "${workspaceFolder}",
在这种模式下，最终的format路径仅仅是一个文件名，VScode自动会在打开的项目中寻找这个文件。就没有缺少中间路径的问题了。可以试下
```
debugger: LuaPanda.lua
cwd:      /Users/wangqing/Downloads/lua-5.3.5 3/src
getinfo:  @./lll/test1.lua
format:   test1.lua     --这里仅保留了文件名，
说明:已开启autoPathMode自动路径模式，调试器会根据getinfo获得的文件名自动查找文件位置，请确保VSCode打开的工程中不存在同名lua文件。
```

如果还有问题，欢迎讨论

**Comment by wzhengsen** [comment]
受教了。
