### ISSUE TITLE
关于代码智能提示的BUG

### ISSUE THREAD

**Issue by wwsstt1994** [Tencent/LuaPanda#58]
比如我的函数名叫GetAccount，在我输入到get之前都是正常的，我再输入a，代码提示会关闭，需要ctrl+space重新唤醒才行

**Comment by stuartwang** [comment]
目前版本的代码提示是大小写敏感的，如果要提示 GetAccount 则必须大小写一致。
我猜测是A输成了小写的，所以没有匹配到结果导致的代码提示关闭。

因为这样确实有点影响使用，我们下个版本会把代码提示改成大小写不敏感。即使输入getaccount , 也可以提示出 GetAccount，解决这类问题。

看下是否是个原因哈

**Comment by wwsstt1994** [comment]
嗯确实是这个原因，然后我在使用其他智能提示插件的时候发现即使不是字符完全按顺序匹配，也可以提示出近似的结果。
举个栗子还是GetAccount，如果我输入getao，也是有GetAccount提示出来的。

**Comment by stuartwang** [comment]
这个和符号搜索方式有关。
比如输入getao，可以提示出GetAccount，这种应该用的是模糊搜索。我们在搜索当前文件符号的时候，也用了类似的方式。（符号名含有 :  ， 但搜索时没有输，也能找到）
![image](https://user-images.githubusercontent.com/16960038/76068028-5d81aa00-5fcb-11ea-9f0a-a6b3ab89b533.png)
我们遇到的问题是：因为要进行大量的匹配，模糊搜索的缺点就是性能比较差。为了支持含有大量lua文件的工程的符号查找，我们把搜索方式换成了顺序搜索，数据结构使用字典树。测试结果在2000个以上lua文件的工程中，全局查找符号时性能也有较好的表现。
