### ISSUE TITLE
Unlua与Luapanda调试时卡死的问题

### ISSUE THREAD

**Issue by hxhb** [Tencent/LuaPanda#60]
复现方法：
1.启动vacode选择项目中的lua文件debug进入LuaPanda Script模式，等待UnLua项目的工程运行
2.启动UE项目，在编辑器Play
这是正常流程没有问题，在运行之后在UE中按ESC退出，此时VSC中的luapanda调试模式也退出了。
3.然后直接在UE中再次点play，此时VSC中的luapanda debug模式自动启动，但不会命中断点，UE卡住。
4.只有在VSC中把luapanda的调试重启或者停止，UE的编辑器才会恢复运行。
之后不管怎么运行都不能在vsc中断点，完全重启vsc和ue之后才可以恢复。

我觉得应该是在esc退出ue的play之后luapanda的监听进程没有关闭？

**Comment by hxhb** [comment]
使用的版本是luapanda 3.1.0

**Comment by stuartwang** [comment]
看起来是连接异常的问题，我先复现一下。 最近我们重新整理了socket的监听和连接逻辑，会尽量在这个版本修复

**Comment by hxhb** [comment]
> 看起来是连接异常的问题，我先复现一下。 最近我们重新整理了socket的监听和连接逻辑，会尽量在这个版本修复

好的，感谢

**Comment by stuartwang** [comment]
文件调试模式指的是这个模式么？
![image](https://user-images.githubusercontent.com/16960038/77315844-3ead4280-6d43-11ea-9f30-bdf1bf2421b5.png)
这个DebugFile 模式的设计初衷是为了方便单个lua文件的调试，用户只要点击运行，就会自动拉起当前VScode活动窗口的lua代码（调用 lua ./xxx.lua），并进入调试状态。不用`require("LuaPanda")` , 也不用把LuaPanda.lua放入工程。目的是方便用户测试一段独立的lua代码执行状况。

正常调试项目的话，用 LuaPanda 模式运行，我们一般调试代码都使用这个模式即可。
之所以在Debug-File模式下会crash, 原因是Debug-File模式会拉起一个独立lua进程，和ue进程端口号冲突了。后面我会把Debug-File的端口号改成8820，避免大家用错时和其他模式冲突。

验证下是否是我说的问题哈

**Comment by hxhb** [comment]
我用的是LuaPanda (Script)这个模式，有点奇怪，有时候在VSC里以Script启动会提示“调试配置 Luapanda已在运行”

**Comment by stuartwang** [comment]
我今天测试了下，没能复现这个问题。说一下我觉认为可能性。

**Comment by stuartwang** [comment]
对了，我重看了下issue ，其中第三步
3.然后直接在UE中再次点play，此时VSC中的luapanda debug模式自动启动，但不会命中断点，UE卡住。
因为调试器本身每次运行后只能手动再次启动，不知道LuaPanda (Script)是否是你们写了一个自动启动VScode 调试的脚本。如果是的话，可能是我们对启动时机的处理不够完善。
现在我们默认接受的启动顺序是，
VSCode 调试启动 ->启动ue ->VSCode 调试停止-> 停止ue      以此为一个周期
如果流程变成了
VSCode 调试启动 ->启动ue -> VSCode 调试停止 -> VSCode 调试启动  -> 停止ue
这样流程就可能会出现问题

我们也在考虑加上 vscode 启动一次，之后可以反复连接进程进行调试的模式，免得大家每次启动ue/unity都要点一下调试启动按钮。
