### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by lijingsmallbee** [Tencent/LuaPanda#61]

**Comment by lijingsmallbee** [comment]
直接下载vscode 1.43.1安装，然后安装luapanda，用的是xlua，然后已经把.txt关联为lua文件，但是还是没有高亮显示

**Comment by stuartwang** [comment]
vscode 中 ,txt 默认是作为文本显示的，需要把在vscode中把TXT 关联成lua文件类型就可以了
![H`5ZB)0`U_Q% T)EHJ5V`85](https://user-images.githubusercontent.com/16960038/77384425-4eb73780-6dc0-11ea-897c-09f5feabf927.png)
