### ISSUE TITLE
多文件夹支持？

### ISSUE THREAD

**Issue by Enzojz** [Tencent/LuaPanda#63]
一般在写一些Steam上的游戏的MOD的时候，MOD代码和游戏主文件夹是不在一个地方的，这个时候调试器就没法正常运行的
是否可以设置多个搜寻路径，或者搜寻所有workspace下的路径
此外我在MOD的游戏里面有多种后缀（.lua, .con .module 等等），但是这个调试器只允许我配置一种后缀，是否可以增加多种后缀的支持？

或者能不能有一个fallback模式，如果callstake里面的文件找不到就忽略，直接定位到可以找到的一层？像C++调试的时候那样，外面的库没有符号库的话就不管了？

**Comment by stuartwang** [comment]
多文件夹的支持已经在做了。当前的目标是可以支持VScode打开多个文件夹，并启动调试（支持多 target 同时调试），多 workspace 也是一个好想法，后续版本我们评估下其必要性，如果多 target不能覆盖这种需求，在考虑实现。

关于多后缀
各种框架的lua虚拟机传给调试器的路径各不相同，取决于框架loadfile时传入的路径。调试器得到的路径有的框架有后缀，有的没有后缀，同时lua支持require(A.B)的形式引用文件，造成取得的路径有很大不确定性，所以为了兼容各种情况，同时也要保证运行效率，路径处理的逻辑比较复杂。
我初步评估了一下，可以实现但较复杂。我们会在后续的版本中再评估。

fallback 是一个很好地建议，我们会尽快实现。

**Comment by stuartwang** [comment]
https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/common-functions.md#%E5%A4%9A%E7%9B%AE%E6%A0%87%E8%B0%83%E8%AF%95-multi-target
3.2.0版本以支持，可以参考文档

**Comment by pilaoda** [comment]
> https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/common-functions.md#%E5%A4%9A%E7%9B%AE%E6%A0%87%E8%B0%83%E8%AF%95-multi-target 3.2.0版本以支持，可以参考文档

这个只支持多虚拟机的情况，能否支持单虚拟机多目录的情况？
