### ISSUE TITLE
调试某些特殊字符串时，造成调试器无法正常工作的问题。

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#68]
**描述**
有一些特殊的字符串，在调试时，导致调试器停止工作。

**环境**
- vscode 1.43.2
- LuaPanda 3.10
- lua5.3

**重现**
```lua
    local chars = {
        202,
        65,
        254,
        4,
        193,
        13
    };
    local str = string.char(table.unpack(chars));-- 此处无法调试str值。
    print(str);
```

**Comment by stuartwang** [comment]
我分别用调试和直接运行都试了下，输出结果乱码的原因可能是字体中无法显示 ascii 中的一些字符

![image](https://user-images.githubusercontent.com/16960038/78205143-038eda00-74ce-11ea-9c4f-a09936ce88c7.png)
![image](https://user-images.githubusercontent.com/16960038/78205165-0c7fab80-74ce-11ea-83b5-0e3580ce5a33.png)

如果遇到的是调试器直接停止，我知道以下两种可能
1.  table.unpack(chars) 是lua 5.2 引入的，留意下lua环境
2. 使用 LuaPanda.getInfo() 检查下 Base64EncodeStr 是否打开。这个选项是对传输数据使用base64加密，避免冲突。如果 isNeedB64EncodeStr 是关闭状态， 传输的json串会出现这样的字段，导致解析失败： `"value":"\"�A��\r\""` 。
![image](https://user-images.githubusercontent.com/16960038/78206673-12778b80-74d2-11ea-8f7e-955a1f41ca11.png)
此项应该是默认开启的，也可以通过launch.json 中添加 ` "isNeedB64EncodeStr":true` 来控制

**Comment by wzhengsen** [comment]
谢谢，发现是isNeedB64EncodeStr被关闭了。
