### ISSUE TITLE
Assets/Game/Lua\libpdebug.lua, file is not existed

### ISSUE THREAD

**Issue by qjf1992** [Tencent/LuaPanda#7]
按照教程的流程走了一遍，在运行时会自动打一行断点并提示该错误，即使是我把该so文件放到plugins下并导入也是不行。但后续的断点都可以正常打到

后续测试：so文件放到Assets/Game/Lua路径下也是不行的。

环境是Unity+xlua。

**Comment by qjf1992** [comment]
![image](https://user-images.githubusercontent.com/11954576/52545091-cd852700-2def-11e9-8955-8db8a8235aa1.png)

检查了一下，该so文件是存在的

**Comment by qjf1992** [comment]
已经解决了，需要手动引入libpdebug到项目中才可以，新手流程上建议追加这一步~

        [DllImport("libpdebug", CallingConvention = CallingConvention.Cdecl)]
        public static extern int luaopen_libpdebug(System.IntPtr L);

        [MonoPInvokeCallback(typeof(lua_CSFunction))]
        public static int LoadLuaPanda(System.IntPtr L)
        {
            return luaopen_libpdebug(L);
        }

**Comment by stuartwang** [comment]
非常感谢~
我们在尝试复现这个问题。想了解一下，Unity 和 VSCode 是运行在同一台机器上么，是Win还是Mac呢？

**Comment by qjf1992** [comment]
你好：
Unity和VSCode是运行在同一台机器上，Win。
这个问题在手动引入dll后解决了，目前已经不报错了。
但是有一个小问题，在VSCode进入调试后（且运行时），会总是自动进行一次Break。
Break的位置是我未添加过断点的位置（应该是代码当前执行到的行）。

> 非常感谢~
> 我们在尝试复现这个问题。想了解一下，Unity 和 VSCode 是运行在同一台机器上么，是Win还是Mac呢？

**Comment by stuartwang** [comment]
> 但是有一个小问题，在VSCode进入调试后（且运行时），会总是自动进行一次Break。
> Break的位置是我未添加过断点的位置（应该是代码当前执行到的行）。

这个是正常的，可以设置 launch.json 中的 `stopOnEntry` 来修改。 stopOnEntry的作用是 设置是否在调试器启动后立刻停止。

**Comment by qjf1992** [comment]
> > 但是有一个小问题，在VSCode进入调试后（且运行时），会总是自动进行一次Break。
> > Break的位置是我未添加过断点的位置（应该是代码当前执行到的行）。
> 
> 这个是正常的，可以设置 launch.json 中的 `stopOnEntry` 来修改。 stopOnEntry的作用是 设置是否在调试器启动后立刻停止。

感谢。目前没有其他问题了：）

**Comment by stuartwang** [comment]
> 感谢。目前没有其他问题了：）

也非常感谢提出问题。关于引用的问题我们会关注并尝试做一下异常处理~
