### ISSUE TITLE
什么时候支持lua5.4,希望适配

### ISSUE THREAD

**Issue by msccreater** [Tencent/LuaPanda#75]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stuartwang** [comment]
感谢，我们最近会测试一下并尝试支持

**Comment by stuartwang** [comment]
今天上午做了简单的测试，在 lua5.4 下可以进行简单代码的调试
