### ISSUE TITLE
希望能支持多虚拟机同时调试

### ISSUE THREAD

**Issue by pilaoda** [Tencent/LuaPanda#76]
UE4本地调试有客户端和服务端的同时使用Lua虚拟机的情况，目前同时监听端口会卡死。希望能支持。

**Comment by stuartwang** [comment]
我们之前有接触到项目会使用多个虚拟机，用不同虚拟机完成相对独立的工作。
当前版本如果用多个虚拟机，同端口连接调试器，因不同虚拟机运行状态不一致，会导致调试器状态乱掉。可以考虑开两个vscode窗口，用不同的端口区分进行调试。

我们在新版本里已经开发多虚拟机支持，并且有业务在试用，效果如下图
![image](https://user-images.githubusercontent.com/16960038/85937279-af608e00-b934-11ea-8d87-9247c2bb0b48.png)
存在于两个虚拟机，UX 和 GamePlay ，可以在一个VScode窗口中同时进行调试，互不干扰。我们进一步测试后会更新使用方法

**Comment by stuartwang** [comment]
看下这份文档中的多目标调试内容，可以从dev分支拉代码打包试一下。
https://github.com/Tencent/LuaPanda/blob/dev/Docs/Manual/common-functions.md
经过后续测试后这个版本会被更新到插件商店

**Comment by stuartwang** [comment]
https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/common-functions.md#%E5%A4%9A%E7%9B%AE%E6%A0%87%E8%B0%83%E8%AF%95-multi-target
3.2.0版本以支持，可以参考文档
