### ISSUE TITLE
点击调试时，一直显示listening.....

### ISSUE THREAD

**Issue by Temozly** [Tencent/LuaPanda#78]
按照文档的方法配置了vscode的调试配置项目，按f5，输出提示说有相同的文件名，之后就一直是listening状态。

**Comment by stuartwang** [comment]
建议检查下 luasocket 是否存在，以及 lua 端是否有导入 luapanda.lua 文件，并使用 require("LuaPanda").start("127.0.0.1",8818); 引用

https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/access-guidelines.md#%E6%8E%A5%E5%85%A5%E5%B7%A5%E4%BD%9C

**Comment by stuartwang** [comment]
https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/debug-on-phone.md#2-%E5%B1%80%E5%9F%9F%E7%BD%91%E8%B0%83%E8%AF%95
如果是真机调试，并通过局域网连接调试，首先检查手机能否ping通pc ,  之后设置一下luapanda.lua 文件头部的配置
![image](https://user-images.githubusercontent.com/16960038/88892213-08467d80-d277-11ea-910b-1c6c7a263ee5.png)
把红框中变量的值改为 0.5 或者 1。 这个值的作用是尝试连接的timeout时间，太小的话在局域网环境下还没建立连接就超时了。
因为等待连接的过程是阻塞的，这个值太大会造成等待连接时卡顿
