### ISSUE TITLE
调试时可以修改变量的值

### ISSUE THREAD

**Issue by stuartwang** [Tencent/LuaPanda#8]
调试时可以在断点处给变量重新赋值。
支持从调试控制台修改和变量展示界面修改两种方式

**Comment by stuartwang** [comment]
功能完成

**Comment by qaz505876013** [comment]
请问是不是不能改table中的值的？改了table中的值，无论是F10还是F11、F5，修改的table都会变回原来的，只能将table的值赋给一个中间变量，然后再将这个中间变量赋给一个新table才能修改。
