### ISSUE TITLE
点击调试一直显示initializing

### ISSUE THREAD

**Issue by JoyChen1998** [Tencent/LuaPanda#80]
luapanda配置什么都都没问题，也没有报什么错。但是输出栏一直显示LuaPanda initializing。
"type": "lua",
            "request": "launch",
            "name": "LuaPanda",
            "luaFileExtension": "lua.txt",
            "connectionPort": 8818,
            "cwd": "${workspaceFolder}Assets/Lua",
            "updateTips": true,
            "pathCaseSensitivity": true,
            "stopOnEntry": true,
            "useCHook": true,
            "autoPathMode": true,
            "logLevel": 1`
  
`require("Debug/LuaPanda").start("127.0.0.1", 8818)`
我使用的是xlua框架，luapanda放到Lua底下的Debug文件夹下。按f5就建立不了连接，状态栏也一直是蓝色

**Comment by stuartwang** [comment]
看起来配置是正确的，尝试看一下lua端运行有没有报错，另外可以尝试看下8818端口是否被别的进程占用

**Comment by JoyChen1998** [comment]
lua端运行应该没有报错，程序一直可以正常运行，同时我也看了下8818端口也没有被占用

**Comment by stuartwang** [comment]
![image](https://user-images.githubusercontent.com/16960038/87739459-74a29500-c812-11ea-91e4-2bde328f6aab.png)
output 的 AdapterLog 没有显示listening... 对么？看起来是插件运行出了问题，想问下运行环境是什么呢？我这边复现一下看看

操作系统： 
lua开发框架：（比如slua/xlua等）
lua版本：

**Comment by JoyChen1998** [comment]
![TIM图片20200717102950](https://user-images.githubusercontent.com/27812683/87742034-7a9b7480-c818-11ea-899b-6aa08ac8f145.png)
操作系统：win10 1607
lua开发框架：xlua
lua版本：5.3

**Comment by stuartwang** [comment]
3.2.0 修复了一些 socket 连接的问题，可以再试下哈
