### ISSUE TITLE
binary expression right var:'startPos' is the same to left var:'startPos'

### ISSUE THREAD

**Issue by skyhuangdan** [Tencent/LuaPanda#81]
https://github.com/Tencent/LuaPanda/blob/29cbcb3eeb169d651044e5cee1c5863bbb124d21/Debugger/LuaPanda.lua#L2856

**Comment by stuartwang** [comment]
This line belongs to JSON4Lua. Check if startPos no assigned, set default value 1. 
Here the author may want to simulate the writing of the trinocular operator： startPos = startPos ? startPos : 1
In Lua, it can be abbreviated as
startPos = startPos or 1
Do you think so?

**Comment by skyhuangdan** [comment]
in this situation，i think : `startPos or 1 ` will be enough.
https://www.lua.org/pil/3.3.html

**Comment by stuartwang** [comment]
I think this situation like the following code, you can try it
```
function test(startPos)
    startPos or 1
    print(startPos)
end

test()
```
![image](https://user-images.githubusercontent.com/16960038/87848367-38565e00-c912-11ea-8665-63d07920801f.png)
