### ISSUE TITLE
当改变launch.json的某些配置时，LuaPanda的设置界面无法进入的问题。

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#82]
**Describe the bug**
当一个工程可以在windows和mac上编译运行并调试时，若为windows和mac配置不同的program路径，
会导致LuaPanda的设置界面无法进入。

**To Reproduce**
1. launch.json配置如下：
```json
"configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "LuaPanda",
            "windows": {
                "program": "${workspaceFolder}/win/win32.exe",
            },
            "osx": {
                "program": "${workspaceFolder}/mac/macApp",
            }
        }
]
```
2. 如果启动调试，在windows和mac上调试都一切正常。
3. 如果企图打开LuaPanda设置页面，这出现如下图错误：

**Screenshots**
![image](https://user-images.githubusercontent.com/30433761/87847290-992d6880-c909-11ea-8cb3-e71a60b9f397.png)

**Desktop**
 - OS: [Windows10]
 - Visual Studio Version [1.47.0]
 - LuaPanda Version [3.1.0]
 - Framework [Native lua53]

**Comment by stuartwang** [comment]
这个 launch.json 改动还是挺大的，很多选项都被删除了，这些被删除的项目都会按默认配置，这点请悉知。
关于错误提示的问题，是因为用的 json  解析器不识别最后一项内容后面的逗号。
我试了下把` "program": "${workspaceFolder}/win/win32.exe",`  和  ` "program": "${workspaceFolder}/mac/macApp", ` 两行最后的逗号去掉就好了。
