### ISSUE TITLE
Could not load source 'Unlua.lua'.

### ISSUE THREAD

**Issue by vandriver** [Tencent/LuaPanda#84]
step into self方法，会提示：
调试器没有找到文件 Unlua.lua 。 请检查launch.json文件中lua后缀是否配置正确, 以及VSCode打开的工程是否正确。
{
            "type": "lua",
            "request": "launch",
            "name": "LuaPanda-Client",
            "program": "",
            "cwd": "${workspaceFolder}",
            "luaFileExtension": "",
            "connectionPort": 8818,
            "pathCaseSensitivity": true,
            "stopOnEntry": false,
            "useCHook": true,
            "autoPathMode": true,
            "logLevel": 1,
}

**Comment by stuartwang** [comment]
Unlua.lua 在unlua工程中是存在的，请确认vscode 打开的文件夹中包含这个文件。
另外不要用workspace的形式打开多文件夹（下个版本会支持），
配置 "name": "LuaPanda-Client", 需要改回  "name": "LuaPanda",  再试一下
