### ISSUE TITLE
调试器没有找到文件 =(tail call).lua 。 请检查launch.json文件中lua后缀是否配置正确, 以及VSCode打开的工程是否正确

### ISSUE THREAD

**Issue by inii** [Tencent/LuaPanda#85]
cocos2d， tolua ，调试器没有找到文件 =(tail call).lua 。 请检查launch.json文件中lua后缀是否配置正确, 以及VSCode打开的工程是否正确

**Comment by stuartwang** [comment]
看起来应该是尾调用被当做了文件的情况，猜测是单补调试时弹出的提示对么，不知道这个错误是否影响调试流程。如果有影响的话，可以如下来做
1. 关闭launch.json文件中的useCHook.   "useCHook": false
2. 在 luapanda.lua 文件的如下位置，模仿红框中的代码，加一下对 =(tail call) 的忽略。这样就不会受到 tail call 干扰了 

![image](https://user-images.githubusercontent.com/16960038/88891678-25c71780-d276-11ea-9261-6ff581243955.png)
