### ISSUE TITLE
在同一项目中，能否支持多种lua文件扩展名

### ISSUE THREAD

**Issue by huashaoz** [Tencent/LuaPanda#86]
比如: lua; config; txt;

**Comment by stuartwang** [comment]
和 #63 有部分相同。因为之前有过提问，所以也做了思考，结论是调试器可以支持多种扩展名。
主要的修改点还是在断点命中阶段做一些处理，但同时要考虑到多框架的兼容情况。我会把这个需求会加入后续的版本计划
