### ISSUE TITLE
100W+文件的工程插件启动很慢

### ISSUE THREAD

**Issue by EricDDK** [Tencent/LuaPanda#88]
大概要3分钟以上的样子，左下角luapanda才会跳出
其中Lua文件5000左右，没有很大的Lua文件

**Comment by stuartwang** [comment]
百万的文件量级确实超出了我们设计时对文件数量的预期。因为插件启动时会调用 path-reader 插件来遍历一下可能的lua文件，并做预分析符号。我觉得可能 path-reader 的遍历也是一个巨大的耗时，我想办法复现一下看能否换用更高效的插件

**Comment by EricDDK** [comment]
> 百万的文件量级确实超出了我们设计时对文件数量的预期。因为插件启动时会调用 path-reader 插件来遍历一下可能的lua文件，并做预分析符号。我觉得可能 path-reader 的遍历也是一个巨大的耗时，我想办法复现一下看能否换用更高效的插件

我修改了一下refresh_FileName_Uri_Cache，现在好了，确实path-reader遍历lua生成100W元素的字符串数组太慢了。
