### ISSUE TITLE
"docPathReplace"配置问题

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#89]
由于某些原因，一些文件需要映射不同路径，如main.lua。
所以，有如下配置：
```json
            "docPathReplace": [
                "${workspaceFolder}/build/bin/${workspaceFolderBasename}/Debug/src/main",
                "${workspaceFolder}/src/main"
            ],
```
在Windows上运行，是正常的，可以正确映射。

但在Android进行远程调试时，必须改为：
```json
            "docPathReplace": [
                "${workspaceFolder}/assets/src/main",
                "${workspaceFolder}/src/main"
            ],
```
否则，无法正确映射。

能否使用如下形式，让两种映射都生效：？
```json
            "docPathReplace": [
                "${workspaceFolder}/build/bin/${workspaceFolderBasename}/Debug/src/main",
                "${workspaceFolder}/src/main",

                "${workspaceFolder}/assets/src/main",
                "${workspaceFolder}/src/main"
            ],
```

**Comment by stuartwang** [comment]
我们更新了一套新的路径方案，叫自动路径，仅用文件名来区分文件，这样就不用再做映射了。不知道这种方案是否能解决问题？

https://github.com/Tencent/LuaPanda/blob/dev/Docs/Manual/access-guidelines.md#%E7%AC%AC%E4%BA%8C%E6%AD%A5-%E8%B7%AF%E5%BE%84%E8%AF%B4%E6%98%8E

**Comment by wzhengsen** [comment]
使用过自动路径，但自动路径会引起的问题是：

**Comment by stuartwang** [comment]
从逻辑角度是可以做到的。但我觉得这个方案从实现上有一些问题，导致性能下降
比如用户设置了
       "docPathReplace": [
                "A/Debug/src/main",
                "B/src/main",

                "C/assets/src/main",
                "B/src/main"
            ],

因为出现了多替换，调试器在hook函数中会先尝试进行路径替换，可能会做多次路径替换。这对性能的影响是很大的。因为hook 函数执行频率非常高，其中的耗时函数都会导致性能下降。
而自动路径采用了另一种思路，把一部分工作（恢复全路径）推到了Vscode插件端去做，调试器lua端只使用文件名进行对比。这样就减轻了hook中路径处理的逻辑。
在下一个版本(3.2.0)中我们会支持自动路径的同名文件处理，还是希望大家尽量使用自动路径模式。 非常感谢提出issue ~

**Comment by wzhengsen** [comment]
感谢解惑。
