### ISSUE TITLE
下列代码无法F12跳转

### ISSUE THREAD

**Issue by EricDDK** [Tencent/LuaPanda#90]
`local M = {}`
`function M:GetLocalAvatarPos()`
    `return "B"`
`end`
`function M:GetLocalAvatarCamp()`
    `return "Blue"`
`end`
`function M:IsTargetLocalAvatar(sTargetCamp, sTargetPos)`
    `return (self:GetLocalAvatarCamp() == sTargetCamp) and (self:GetLocalAvatarCamp() == sTargetPos)`
`end`
`return M`

self:GetLocalAvatarCamp 和 self:GetLocalAvatarCamp() 无法跳转,但是自动补全什么都是正常的

**Comment by stuartwang** [comment]
非常感谢，我有空会试一下，之后规划下重构代码分析部分
