### ISSUE TITLE
attach怎么用?

### ISSUE THREAD

**Issue by widrin** [Tencent/LuaPanda#91]
我在程序启动后再运行LuaPanda，只能在开始的时候暂停，但无法在断点处暂停，请问可以出个attach的文档吗？

**Comment by widrin** [comment]
打印显示LuaPanda已经连接了，就是不能断点，why？

**Comment by widrin** [comment]
似乎是有些地方跳转不到，例如协程，这个还需要研究一下下

**Comment by stuartwang** [comment]
1. 最近有点忙，刚看到消息。关于断点不停止的问题可以看下这里 ： “执行到断点处无法停止” 小节
https://github.com/Tencent/LuaPanda/blob/b6cec30937700611624aae990c5d128ba3dd73ee/Docs/Manual/FAQ.md#%E6%89%A7%E8%A1%8C%E5%88%B0%E6%96%AD%E7%82%B9%E5%A4%84%E6%97%A0%E6%B3%95%E5%81%9C%E6%AD%A2

2. 不能断点的一种可能性是有些框架的lua文件后缀是 txt ，这样vscode不会把他们当做lua文件，所以无法在IDE中打断点

3. 关于协程，只有在 reuqire("LuaPanda").start() 之后的协程才能被hook住，可以试下哈
