### ISSUE TITLE
是否有支持环境变量的方案？

### ISSUE THREAD

**Issue by wzhengsen** [Tencent/LuaPanda#93]
在Linux下进行调试时，可能需要通过临时的环境变量来指定运行时链接库路径，如：
```sh
export LD_LIBRARY_PATH=myPath:$LD_LIBRARY_PATH
```
通过gdb调试c++时，有如下配置可以指定：
![image](https://user-images.githubusercontent.com/30433761/94370229-61207e00-0121-11eb-9518-38b067594612.png)

而我通过LuaPanda调试lua时，会因为未指定环境变量而无法启动。

有时候，环境变量是临时的，所以我并未直接写入.bashrc或.profile。为了lua调试能正常运行，我不得不使用一些“不光彩”的手段来炮制我的代码，以更***丑陋***的方式来实现。

对于这种情况，可以有解决方案吗？

**Comment by stuartwang** [comment]
感谢提出问题。因为我们自己主要是做客户端开发，使用场景主要是win, 其次是mac，linux下确实没有覆盖到。
关于这个问题我的思路是在package.path文件中加一个配置项，也可以叫做 evironment，允许用户配置一些参数。之后在调试器启动时，extension.ts 或者 luaDebug.ts 中读取用户配置的参数并启动一个terminal完成环境配置。

因为最近项目太忙了，所以可能暂时没有精力添加新功能。如果有兴趣可以按照上面的思路拉一个分支尝试开发下
